<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$member = new Member();
    $member->populate(decode($request->id));
	$id = $member->getID();
	
	$isme = true;
	if($member->getID() != $userid){
		$isme = false;
	}
	
	$posturl = "";
	
	$tab = $request->tab;
	if(isEmptyString($tab)){
		$tab = 'overview';
		if($request->detect == '1'){
			$posturl = $this->baseUrl("member/processgps");
		}
	}
	
	$entityname = "Member";
	$listitems = "Members";
	$listurl = $this->baseUrl('member/list');
	$viewurl = $this->baseUrl('member/view/id/'.encode($member->getID()));
	$indexurl = $this->baseUrl('member/index/id/'.encode($member->getID()));
	$title = $member->getName();
	$description = 'Profile Details';	
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Members / '.$member->getName(); ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="icon-large icon-group"></span>');
	
	$("ul.nav.nav-tabs li a").click(function(){
		var url = $(this).attr('goto');
		var id = $(this).attr('theid');
		if(!isEmptyString(url) && url != 'undefined'){
			$(".tab-content #"+id).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/ui-anim_basic_16x16.gif'); ?>' /></a>").css({'display':'block'});
			window.location.href = url;
		}
	}); 
});
</script>
<div class="row-fluid margin0 view">
    <div class="col-md-12 padding0">
    	<div class="headerbox">
            <table class="table border0 nohover margin0">                       
                <tr>		                    
                    <td class="padding2">
                        <div class="btn-group gridactions">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle noround" data-toggle="dropdown">Actions <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu" style="left:-86px;">
                                <?php if ($acl->checkPermission('Member', ACTION_EDIT)) { ?>
                                    <li><a class="blockanchor" href="<?php echo $indexurl; ?>"><i class="glyphicon glyphicon-pencil"></i>&nbsp; Update</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission('Member', ACTION_DELETE)) { ?>
                                    <li><a class="deleteline gonowhere" action="<?php echo $this->baseUrl('member/delete/id/'.encode($member->getID())."/entityname/".$entityname."/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete Entry"><i class="glyphicon  glyphicon-trash"></i>&nbsp; Delete</a></li>
                                <?php } ?>
								<?php if ($acl->checkPermission('Member', ACTION_LIST)) { ?>
                                    <li><a class="blockanchor" href="<?php echo $listurl; ?>"><i class="glyphicon glyphicon-list"></i>&nbsp; List <?php echo $listitems; ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php if ($sessionhaserror) { ?>
    	<div class="alert alert-danger fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
	<?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('invitesuccess'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('invitesuccess'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage1'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage1'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage5'))) { ?>
        <div class="alert alert-warning fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage5'); ?></div>
    <?php } ?>
    <?php if(!isEmptyString($member->hasPendingActivation()) && $acl->checkPermission('Member', ACTION_CREATE)) { ?>
        <div class="alert alert-warning fade in">Activation pending from user</div>
    <?php } ?>
    <?php if($acl->checkPermission('Member', ACTION_DELETE) && $member->isDeactivated()) { ?>
        <div class="alert alert-warning fade in">User profile was de-activated</div>
    <?php } ?>
    <div class="contentcontainer clearfix padding10" style="margin-bottom:10px;">
        <form class="form-horizontal clearfix" id="viewform" action="<?php echo $posturl; ?>" method="post">
            <div class="row margin0">
                <div class="col-md-12" style="padding-left:15px;">
                    <!-- Tabs-->
                    <div class="tabbable tabbable-custom tabbable-full-width">
                        <ul class="nav nav-tabs">
                            <?php if ($acl->checkPermission('Member', ACTION_VIEW)) { ?>
                                <li class="<?php echo $tab == 'overview' ? 'active gonowhere' : 'blockanchor'; ?>"><a href="#overview" goto="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID())); ?>" theid="overview" data-toggle="tab">Overview</a></li>
                            <?php } ?>
                            <?php if ($acl->checkPermission('Member', ACTION_EDIT) || ($isme)) { ?>
                                <li><a href="#updateaccount" class="blockanchor" theid="updateaccount" goto="<?php echo $this->baseUrl('member/index/id/'.encode($member->getID())); ?>" data-toggle="tab">Update Profile</a></li>
                            <?php } ?>
                            <?php if($tab == 'roles'){ ?>
                                <li class="<?php echo $tab == 'roles' ? 'active gonowhere' : ''; ?>"><a>Leadership Roles</a></li>
                            <?php } ?>
                            <?php if($tab == 'bio'){ ?>
                                <li class="<?php echo $tab == 'bio' ? 'active gonowhere' : ''; ?>"><a>Biography</a></li>
                            <?php } ?>
                            <?php if($tab == 'contact'){ ?>
                                <li class="<?php echo $tab == 'contact' ? 'active gonowhere' : ''; ?>"><a>Contact Member</a></li>
                            <?php } ?>
                            <?php if($tab == 'account'){ ?>
                                <li class="<?php echo $tab == 'account' ? 'active gonowhere' : ''; ?>"><a>Account</a></li>
                            <?php } ?>
                        </ul>
                        <div class="divider5"></div>
                        <div class="tab-content row">
                            <div class="tab-pane active" id="overview">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="list-group">
                                            <li class="list-group-item no-padding" style="padding-left:15px; padding-right:15px; padding-bottom:10px;">
                                                <div class="divider5"></div>
                                                <?php if($isme || isAdmin()){ ?>
                                                    <a href="<?php echo $this->baseUrl('member/index/id/'.encode($member->getID()).'/tab/picture'); ?>" class="editpic imagecontainer blockanchor" title="Update Profile Photo"><img id="profileimage" class="imagecontainer" src="<?php echo $member->getMediumPicturePath(); ?>" style="width:100%; height:auto;" /><pre id="uploadlink" class=""><i class="icon-pencil"></i> Upload Photo</pre></a>
                                                <?php } else { ?>
                                                    <img id="profileimage" class="imagecontainer" src="<?php echo $member->getMediumPicturePath(); ?>" style="width:100%; height:auto;" />
                                                    <div class="divider10"></div>
                                                <?php } ?>
                                            </li>
                                            <a class="list-group-item <?php echo $tab == 'overview' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID())); ?>">Profile</a>
                                            
                                            <a class="list-group-item <?php echo $tab == 'roles' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/roles'); ?>">Leadership Roles</a>
                                            <a class="list-group-item <?php echo $tab == 'bio' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/bio'); ?>">Biography</a>
                                            <a class="list-group-item <?php echo $tab == 'contact' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/contact'); ?>">Contact Member</a>
											<a class="list-group-item <?php echo $tab == 'account' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/account'); ?>">Account</a>
                                            <?php if($tab == 'overview'){ ?>
                                                <a class="list-group-item <?php echo $tab == 'xxx' ? 'gonowhere active' : 'gonowhere'; ?>" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/xxx'); ?>">&nbsp;</a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-md-9 paddingleft0">
                                    	<?php if($tab == 'overview'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Summary</legend>
                                                        <div class="panel-body well-sm">
                                                            <div class="row-fluid marginleft5">
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_firstname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getFirstName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_lastname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getLastName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_othernames_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getOtherName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_displayname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getdisplayname(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_gender_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getGenderText(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nationality_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getCountryName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_dateofbirth_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($member->getDateofBirth()); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                    	<label class="col-md-4 control-label"><?php echo $this->translate('profile_maritalstatus_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getAllMaritalStatuses($member->getMaritalStatus(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_suffix_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getSalutations($member->getSalutation(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_profession_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getProfessions($member->getProfession(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                            </div>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Church / Ministry Organisation</legend>
                                                        <div class="panel-body well-sm">
                                                            <div class="row-fluid marginleft5">
                                                                <div class="col-md-12 paddingleft10">
                                                                    <div class="form-group">
                                                                        <div class="col-md-12">
                                                                            <p class="form-control-static nullifempty view gonowhere"><a href="<?php echo $this->baseUrl('organisation/view/id/'.encode($member->getOrganisationID())); ?>"><?php echo $member->getOrganisation()->getName(); ?></a></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                            </div>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Contact</legend>
                                                        <div class="panel-body well-sm">
                                                            <div class="row-fluid marginleft5">
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_phone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getPhone(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_altphone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getPhone2(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_email_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getEmail(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_altemail_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getEmail2(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-6 paddingleft10">
                                                                	<div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nxtkeen_name_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo isEmptyString($member->getContactID()) ? $member->getContactName() : $member->getContact()->getName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nxtkeen_phone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo isEmptyString($member->getContactID()) ? $member->getContactPhone() : $member->getContact()->getPhone(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nxtkeen_rship_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getRelationshipTypes($member->getContactRshp(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if($tab == 'roles'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Leadership Roles and Committees</legend>
                                                        <div class="panel-body well-sm minheight400">
                                                        
                                                        </div>
                                                   	</fieldset>
                                              	</div>
                                        	</div>
                                       	<?php } ?>
                                        <?php if($tab == 'bio'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Biography</legend>
                                                        <div class="panel-body well-sm minheight400">
                                                        
                                                        </div>
                                                   	</fieldset>
                                              	</div>
                                        	</div>
                                       	<?php } ?>
                                        <?php if($tab == 'contact'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Contact <?php echo $member->getName(); ?></legend>
                                                        <div class="panel-body well-sm minheight400">
                                                        
                                                        </div>
                                                   	</fieldset>
                                              	</div>
                                        	</div>
                                       	<?php } ?>
                                        <?php if($tab == 'account'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Account Settings</legend>
                                                        <div class="panel-body well-sm minheight400">
                                                        
                                                        </div>
                                                   	</fieldset>
                                              	</div>
                                        	</div>
                                       	<?php } ?>
                                    </div>
                                </div>
                                <?php if($tab == 'overview'){ ?>
                                    <div class="row-fluid margin0">
                                        <div class="col-md-12 paddingleft0">
                                            <fieldset class="fieldsetcontainer" style="margin-top:0;">
                                                <legend>Location</legend>
                                                <div class="col-md-8">
                                                    <div class="divider5"></div>
                                                    <div class="well clearfix makerelative" style="min-height:325px; height:auto; background-color:#fcfcfc; margin-bottom:10px;">
                                                        <?php if(isEmptyString($request->detect)){ ?>
                                                            <?php if(false){ ?>
                                                            <a class="btn btn-xs btn-default makeabsolute gonowhere" style="top:-10px; right:10px;" href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/detect/1'); ?>"><?php echo $member->hasGPSCoordinates() ? 'Update Position' : 'Locate on map'; ?></a>
                                                            <?php } ?>
                                                            <a class="btn btn-xs btn-default makeabsolute gonowhere" style="top:-10px; right:10px;">Location Map</a>
                                                            <div id="map_canvas" class="gmaps"></div>
                                                        <?php } else { ?>
                                                                <div id="current" class="xbolded">Initializing... Please wait... </div>
                                                                <div class="divider10"></div>	
                                                                <a href="<?php echo $this->referer; ?>" class="btn btn-sm"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                                                <a href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getID()).'/detect/1'); ?>" class="btn btn-sm btn-inverse"><i class="icon-refresh"></i> Reload</a>
                                                                <button type="submit" class="btn btn-sm btn-success hide" id="saveposition"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save')." Position"; ?></button>
                                                                <div class="form-group">
                                                                    <div id="hasgps_error"></div>
                                                                </div>
                                                                <div id="map_canvas" class="span12" style="height:400px; width:100%; margin-left:0;"></div>
                                                                <div class="divider20"></div>	
                                                                <input type="hidden" name="entityname" value="Member" />
                                                                <input type="hidden" id="id" name="id" value="<?php echo encode($member->getID()); ?>" />
                                                                <input type="hidden" id="hasgps" name="hasgps" value="" />
                                                                <input type="hidden" id="lat" name="lat" value="" />
                                                                <input type="hidden" id="lng" name="lng" value="" />
                                                                <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('member/view/id/'.encode($member->getID()))); ?>" />
                                                                <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('member/view/id/'.encode($member->getID()).'/detect/1')); ?>" />
                                                                <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 locations">
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_region_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getRegion()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_province_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getProvince()->getName(); ?></div>
                                                    </div>                                        
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_district_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getDistrict()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_county_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getCounty()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_subcounty_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getSubcounty()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_parish_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getParish()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_village_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getVillage()->getName(); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label"><?php echo $this->translate("global_address_label"); ?>:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo nl2br($member->getAddress1()).''.nl2br($member->getAddress2()); ?></div>
                                                    </div>
                                                    <div class="form-group clearfix">
                                                        <label class="col-md-3 control-label">GPS:</label>
                                                        <div class="col-md-9 nullifempty"><?php echo $member->getGPSCordinates(); ?></div>
                                                    </div>
                                                </div>
                                            </fieldset>                                                                        
                                        </div>
                                    </div>
                                <?php } ?>
                        	</div>
                        </div>
                    </div>
                </div>
            </div>
        </form>   
    </div>                 
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
