<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$user->populate($userid); 
	
	$member = new Member();
	$theid = is_numeric($request->id) ? $request->id : decode($request->id);
    $member->populate($theid);
	$id = $member->getID();
	
	$isme = true;
	if($member->getID() != $userid){
		$isme = false;
	}
	
	$posturl = '';
	$formid = 'viewform';
	$formmethod = 'get';
	
	$isuser = false; $ismember = true;
	if($controller == 'profile'){
		$isuser = true; $ismember = false;
	}
	
	$tab = $request->tab;
	if(isEmptyString($tab)){
		$tab = 'overview';
		if($request->detect == '1'){
			$posturl = $this->baseUrl($controller."/processgps");
		}
	}
	
	if($tab == 'leadership'){
		$formid = 'indexform';
		$formmethod = 'post';
		$posturl = $this->baseUrl("appointment/create");
		$successurl = encode($this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/leadership'));
		$failureurl =  encode($this->viewurl);
		$successmessage = $this->translate('global_save_success');
		$button_title = "Save";
		if(!isEmptyString($request->rid)){
			$button_title = "Save Changes";
			$successmessage = $this->translate('global_update_success');
			$posturl = $this->baseUrl("appointment/edit");
		}
		if(!isEmptyString($request->rid) && !isEmptyString($request->terminate)){
			$button_title = "Terminate Appointment";
		}
		$step = $request->step;
		if(isEmptyString($step)){
			$step = 'list';
		}
		
		$role = new Appointment();
		$subtitle = 'New Appointment';
		if(!isEmptyString($request->rid)){
			$subtitle = 'Update Appointment';
			$role->populate(decode($request->rid));
			if(!isEmptyString($request->terminate)){
				$role->setStatus('0');
			}
		} else {
			$role->setMemberID($member->getID());
		}
		
		$regionid = $role->getRegionID();
		$provinceid = $role->getProvinceID();
		$districtid = $role->getDistrictID();
		$subcountyid = $role->getSubcountyID();
	}
	
	if($tab == 'bio'){
		$step = $request->step;
		if(isEmptyString($step)){
			$step = 'view';
		}
		$subtitle = 'Biography';
		if($step == 'edit'){
			$subtitle = 'Update Biography';
		}
		$formid = 'indexform';
		$formmethod = 'post';
		$posturl = $this->baseUrl("member/updatebio");
		$successurl = encode($this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/bio'));
		$failureurl =  encode($this->viewurl);
		$button_title = "Save Changes";
		$successmessage = $this->translate('global_update_success');
	}
	
	if($tab == 'contact'){
		$step = $request->step;
		if(isEmptyString($step)){
			$step = 'view';
		}
		$subtitle = 'Contact Member';
		$formid = 'indexform';
		$formmethod = 'post';
		$posturl = $this->baseUrl("notifications/processnotification");
		$successurl = encode($this->baseUrl('member/view/id/'.encode($member->getID()).'/tab/bio'));
		$failureurl =  encode($this->viewurl);
		
		$message = new Message();
		$type = $request->type;
		$ismail = true; $issms = false;
		if(isEmptyString($type)){
			$type = 1;
		}
		if($type == 2){
			$issms = true; $ismail = false;
		}
		
		if($ismail){
			$title = "Compose Message";
			$button_title = "Send Message";
			$emailmembers = getMembersWithEmail();
			$emailusers = getMembersWithEmail(true);
		}
		if($issms){
			$title = "Compose SMS";
			$button_title = "Send SMS";
			$phonemembers = getMembersWithPhone();
			$phoneusers = getMembersWithPhone(true);
		}
		
		$subject = ''; $message = '';
		if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
			$formvalues = $session->getVar(FORM_VALUES);		
			$subject = isArrayKeyAnEmptyString('subject', $formvalues) ? '' : $formvalues['subject'];
			$message = isArrayKeyAnEmptyString('message', $formvalues) ? '' : $formvalues['message'];
		}
	}
	
	$resourcename = 'Member';
	$entityname = "Member";
	$listitems = "Members";	
	$viewurl = $this->baseUrl($controller.'/view/id/'.encode($member->getID()));
	$indexurl = $this->baseUrl($controller.'/index/id/'.encode($member->getID()));
	$title = $member->getName();
	$description = 'Profile Details';	
	$icon = 'icon-large icon-group';
	
	if($isuser){
		$resourcename = 'User Account';
		$entityname = "Member";
		$listitems = "Users";
		$icon = 'glyphicon glyphicon-user';
	}
	
	$allowedit = false;
	if($acl->checkPermission($resourcename, ACTION_EDIT)){
		$allowedit = true;
		if($user->isRegionalClerk() && ($member->getRegionID() != $user->getRegionID())){
			$allowedit = false;
		}
		if($user->isProvinceClerk() && ($member->getProvinceID() != $user->getProvinceID())){
			$allowedit = false;
		}
		if($user->isDistrictClerk() && ($member->getDistrictID() != $user->getDistrictID())){
			$allowedit = false;
		}
		if($user->isSubCountyClerk() && ($member->getSubcountyID() != $user->getSubcountyID())){
			$allowedit = false;
		}
	}
	
	$listurl = $this->baseUrl($controller.'/list');
	$customurl = '';
	if($user->isRegionalClerk()){
		$customurl = '/regionid/'.$user->getRegionID();
	}
	if($user->isProvinceClerk()){
		$customurl = '/provinceid/'.$user->getProvinceID();
	}
	if($user->isDistrictClerk()){
		$customurl = '/districtid/'.$user->getDistrictID();
	}
	if($user->isSubCountyClerk()){
		$customurl = '/subcountyid/'.$user->getSubcountyID();
	}
	$listurl = $listurl.$customurl;
	
	$loadgps = loadMaps();
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$listitems.' / '.$member->getName(); ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	// forward any attempt to view a member as a non existing user
	<?php if(!isEmptyString($member->getID()) && isEmptyString($member->getType()) && $controller == 'profile'){ ?>
		var url = '<?php echo str_replace('/profile/', '/member/', $this->viewurl); ?>'; // alert(url);
		window.location.href = url;
	<?php } ?>

});
</script>
<div class="row-fluid margin0 view">
    <div class="col-md-12 padding0">
    	<div class="headerbox">
            <table class="table border0 nohover margin0">                       
                <tr>		                    
                    <td class="padding2">
                        <div class="btn-group gridactions">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle noround" data-toggle="dropdown">Actions <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu" style="left:-86px;">
                                <?php if($allowedit) { ?>
                                    <li><a class="blockanchor" href="<?php echo $indexurl; ?>"><i class="glyphicon glyphicon-pencil"></i>&nbsp; Update</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission($resourcename, ACTION_DELETE)) { ?>
                                    <li><a class="<?php echo $member->isUserActive() ? 'alert-dialog' : 'deleteline'; ?> gonowhere" action="<?php echo $this->baseUrl($controller.'/delete/id/'.encode($member->getID())."/entityname/Member/successurl/".encode($listurl)); ?>" message="<?php echo $member->isUserActive() ? 'Delete on this Profile is  disabled. Contact Super Admin' : $this->translate('global_delete_confirm_message'); ?>" title="Delete Entry"><i class="glyphicon  glyphicon-trash"></i>&nbsp; Delete</a></li>
                                <?php } ?>
								<?php if ($acl->checkPermission($resourcename, ACTION_LIST)) { ?>
                                    <li><a class="blockanchor" href="<?php echo $listurl; ?>"><i class="glyphicon glyphicon-list"></i>&nbsp; List <?php echo $listitems; ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php if ($sessionhaserror) { ?>
    	<div class="alert alert-danger fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
	<?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('invitesuccess'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('invitesuccess'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage1'))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage1'); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar('custommessage5'))) { ?>
        <div class="alert alert-warning fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar('custommessage5'); ?></div>
    <?php } ?>
    <?php if(!isEmptyString($member->hasPendingActivation()) && $acl->checkPermission("User Account", ACTION_CREATE) ) { ?>
        <div class="alert alert-warning fade in">Activation pending from user</div>
    <?php } ?>
    <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && $member->isDeactivated()) { ?>
        <div class="alert alert-warning fade in">User profile was de-activated</div>
    <?php } ?>
    <div class="contentcontainer clearfix padding10" style="margin-bottom:10px;">
        <form id="<?php echo $formid; ?>" class="form-horizontal" role="form" method="<?php echo $formmethod; ?>" action="<?php echo $posturl; ?>">
            <div class="row margin0">
                <div class="col-md-12" style="padding-left:15px;">
                    <!-- Tabs-->
                    <div class="tabbable tabbable-custom tabbable-full-width">
                        <ul class="nav nav-tabs">
                            <?php if ($acl->checkPermission($resourcename, ACTION_VIEW)) { ?>
                                <li class="<?php echo $tab == 'overview' ? 'active' : ''; ?>"><a href="#overview" class="<?php echo $tab == 'overview' ? 'gonowhere' : 'blockanchor'; ?>" goto="<?php echo $tab == 'overview' ? '' : $this->baseUrl($controller.'/view/id/'.encode($member->getID())); ?>" theid="overview" data-toggle="tab">Overview</a></li>
                            <?php } ?>
                            <?php if ($allowedit || $isme) { ?>
                                <li><a href="#updateaccount" class="blockanchor" theid="updateaccount" goto="<?php echo $this->baseUrl($controller.'/index/id/'.encode($member->getID())); ?>" data-toggle="tab">Update Profile</a></li>
                            <?php } ?>
                            <?php if($tab == 'leadership'){ ?>
                                <li class="<?php echo $tab == 'leadership' ? 'active gonowhere' : ''; ?>"><a>Leadership Roles</a></li>
                            <?php } ?>
                            <?php if($tab == 'bio'){ ?>
                                <li class="<?php echo $tab == 'bio' ? 'active gonowhere' : ''; ?>"><a>Biography</a></li>
                            <?php } ?>
                            <?php if($tab == 'contact' && !$isme){ ?>
                                <li class="<?php echo $tab == 'contact' ? 'active gonowhere' : ''; ?>"><a>Contact Member</a></li>
                            <?php } ?>
                            <?php if($tab == 'account'){ ?>
                                <li class="<?php echo $tab == 'account' ? 'active gonowhere' : ''; ?>"><a>Account</a></li>
                            <?php } ?>
                        </ul>
                        <div class="divider5"></div>
                        <div class="tab-content row">
                            <div class="tab-pane active" id="overview">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="list-group">
                                            <li class="list-group-item no-padding" style="padding-left:15px; padding-right:15px; padding-bottom:10px;">
                                                <div class="divider5"></div>
                                                <?php if($allowedit || $isme){ ?>
                                                    <a href="<?php echo $this->baseUrl($controller.'/index/id/'.encode($member->getID()).'/tab/picture'); ?>" class="editpic imagecontainer blockanchor" title="Update Profile Photo"><img id="profileimage" class="imagecontainer" src="<?php echo $member->getMediumPicturePath(); ?>" style="width:100%; height:auto;" /><pre id="uploadlink" class=""><i class="icon-pencil"></i> Upload Photo</pre></a>
                                                <?php } else { ?>
                                                    <img id="profileimage" class="imagecontainer" src="<?php echo $member->getMediumPicturePath(); ?>" style="width:100%; height:auto;" />
                                                    <div class="divider10"></div>
                                                <?php } ?>
                                            </li>
                                            <a class="list-group-item <?php echo $tab == 'overview' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl($controller.'/view/id/'.encode($member->getID())); ?>">Profile</a>
                                            <a class="list-group-item <?php echo $tab == 'bio' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl($controller.'/view/id/'.encode($member->getID()).'/tab/bio'); ?>">Biography</a>
                                            <a class="list-group-item <?php echo $tab == 'leadership' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl($controller.'/view/id/'.encode($member->getID()).'/tab/leadership'); ?>">Leadership Roles</a>
                                            <?php if(!$isme){ ?>
                                            	<a class="list-group-item <?php echo $tab == 'contact' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl($controller.'/view/id/'.encode($member->getID()).'/tab/contact'); ?>">Contact Member</a>
                                            <?php } ?>
                                            <?php if($member->isUserActive() && ($isme || $acl->checkPermission("User Account", ACTION_DELETE))){ ?>
												<a class="list-group-item <?php echo $tab == 'account' ? 'gonowhere active' : 'blockanchor'; ?>" href="<?php echo $this->baseUrl($controller.'/view/id/'.encode($member->getID()).'/tab/account'); ?>">Account</a>
                                            <?php } else { ?>
                                            	<a></a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-md-9 paddingleft0">
                                    	<?php if($tab == 'overview'){ ?>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
                                                        <legend>Summary</legend>
                                                        <div class="panel-body well-sm">
                                                            <div class="row-fluid marginleft5">
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_firstname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getFirstName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_lastname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getLastName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_othernames_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getOtherName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_displayname_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getdisplayname(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_gender_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getGenderText(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nationality_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getCountryName(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_dateofbirth_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo changeMySQLDateToPageFormat($member->getDateofBirth()); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                    	<label class="col-md-4 control-label"><?php echo $this->translate('profile_maritalstatus_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getAllMaritalStatuses($member->getMaritalStatus(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_suffix_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getSalutations($member->getSalutation(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_profession_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getProfessions($member->getProfession(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                            </div>
                                            <div class="row-fluid margin0">
                                                <div class="col-md-12">
                                                    <fieldset class="fieldsetcontainer" style="margin-bottom:0; <?php echo $member->isUserActive() ? 'min-height:230px' : ''; ?>">
                                                        <legend>Contact</legend>
                                                        <div class="panel-body well-sm">
                                                            <div class="row-fluid marginleft5">
                                                                <div class="col-md-6 paddingleft10">
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_phone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getPhone(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_altphone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getPhone2(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_email_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getEmail(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_altemail_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo $member->getEmail2(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-6 paddingleft10">
                                                                	<div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nextkin_name_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view">
																			<?php if(isEmptyString($member->getContactID()) && !isEmptyString($member->getContactName())){ ?>
                                                                            	<?php echo $member->getContactName(); ?>
                                                                            <?php } ?>
                                                                            <?php if(!isEmptyString($member->getContactID()) && isEmptyString($member->getContactName())){ ?>
                                                                            	<a href="<?php echo $this->baseUrl('member/view/id/'.encode($member->getContactID())); ?>" class="blockanchor"><?php echo $member->getContact()->getName(); ?></a>
                                                                            <?php } ?>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nextkin_phone_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo isEmptyString($member->getContactID()) ? $member->getContactPhone() : $member->getContact()->getPhone(); ?></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label class="col-md-4 control-label"><?php echo $this->translate('profile_nextkin_rship_label'); ?>:</label>
                                                                        <div class="col-md-8">
                                                                            <p class="form-control-static nullifempty view"><?php echo getRelationshipTypes($member->getContactRshp(), true); ?></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if($tab == 'bio'){ ?>
                                            <?php require APPLICATION_PATH."/views/scripts/member/bio.phtml"; ?>
                                       	<?php } ?>
                                        <?php if($tab == 'leadership'){ ?>
                                            <?php require APPLICATION_PATH."/views/scripts/appointment/index.phtml"; ?>
                                       	<?php } ?>
                                        <?php if($tab == 'contact' && !$isme){ ?>
	                                        <?php require APPLICATION_PATH."/views/scripts/member/contact.phtml"; ?>
                                       	<?php } ?>
                                        <?php if($tab == 'account'){ ?>
                                            <?php require APPLICATION_PATH."/views/scripts/member/account.phtml"; ?>
                                       	<?php } ?>
                                    </div>
                                </div>
                                <?php if($tab == 'overview'){ ?>
                                	<div class="row-fluid margin0">
                                        <div class="col-md-12 paddingleft0">
                                            <fieldset class="fieldsetcontainer">
                                                <legend>Church / Ministry Organisation</legend>
                                                <div class="panel-body well-sm">
                                                    <div class="row-fluid marginleft5">
                                                        <div class="col-md-12 paddingleft10">
                                                            <div class="form-group">
                                                                <div class="col-md-12">
                                                                    <p class="form-control-static nullifempty view gonowhere"><a href="<?php echo $this->baseUrl('organisation/view/id/'.encode($member->getOrganisationID())); ?>"><?php echo $member->getOrganisation()->getName(); ?></a></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </fieldset>
                                        </div>
                                    </div>
                                    <div class="row-fluid margin0">
                                        <div class="col-md-12 paddingleft0">
                                            <fieldset class="fieldsetcontainer" style="margin-top:0;">
                                                <legend>Location</legend>
                                                <?php if(!$member->hasGPSCoordinates()){ ?>
                                                    <div class="panel-body well-sm">
                                                        <div class="row-fluid marginleft5">
                                                            <div class="col-md-6">
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_region_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getRegion()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_province_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getProvince()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_district_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getDistrict()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_county_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getCounty()->getName(); ?></div>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                            	<div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_subcounty_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getSubcounty()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_parish_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getParish()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_village_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getVillage()->getName(); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label"><?php echo $this->translate("global_address_label"); ?>:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo nl2br($member->getAddress1()).''.nl2br($member->getAddress2()); ?></div>
                                                                </div>
                                                                <div class="form-group clearfix">
                                                                    <label class="col-md-3 control-label">GPS:</label>
                                                                    <div class="col-md-9 nullifempty"><?php echo $member->getGPSCordinates(); ?></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="divider2"></div>
                                                <?php } else { ?>
                                                	<?php if($loadgps && $member->hasGPSCoordinates()){ ?>
														<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/geoPosition.js')); ?>"></script>
                                                        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&key=AIzaSyAjkTHnLzEkyF1ntVoUkZthaZWV4VN5DJE"></script>
                                                    <?php } ?>
                                                	<script>
														$(document).ready(function() {
															<?php if($member->hasGPSCoordinates() && isEmptyString($request->detect) && $loadgps){ ?>
																var gpslat = '<?php echo $member->getGPSlat(); ?>';
																var gpslng = '<?php echo $member->getGPSlng(); ?>';
																var title = "<?php echo $isme ? 'My Location' : $member->getFirstName()."'s Location "; ?>";
															<?php } ?>
														}); 
														
														$(window).load(function() {
															<?php if($member->hasGPSCoordinates()){ ?>
																initialiseMap(); 
																showPosition(); 
															<?php } ?>
															
															// initialise the google map
															function initialiseMap(){
																var myOptions = {
																	zoom: 4,
																	mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
																	navigationControl: true,
																	navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
														  
																	scrollwheel: false,
																	mapTypeControl: false,
																	scaleControl: true,
																	mapTypeId: google.maps.MapTypeId.ROADMAP, // google map type
																	zoom: 8
																}        
																map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
															}
															
															function showPosition(){
																var latitude = '<?php echo $member->getGPSLat(); ?>';
																var longitude = '<?php echo $member->getGPSLng(); ?>';
																var pos = new google.maps.LatLng(latitude, longitude);
																map.setCenter(pos);
																map.setZoom(14);
														
																var infowindow = new google.maps.InfoWindow({
																	content: "<b><?php echo $member->getName(); ?>'s Location</b> <br /><br /> Latitude = "+latitude+ " <br />Longitude = "+longitude
																});
														
																var marker = new google.maps.Marker({
																	position: pos,
																	map: map,
																	title:"<?php echo $member->getName(); ?>'s Location"
																});
														
																google.maps.event.addListener(marker, 'click', function() {
																  infowindow.open(map,marker);
																});
															}
														});	
													</script>
                                                    <div class="divider10"></div>
                                                    <div class="col-md-8">
                                                        <div class="divider5"></div>
                                                        <div class="well clearfix makerelative" style="min-height:300px; height:auto; background:none; background-color:#F9f9fa; margin-bottom:10px; padding:5px;">
                                                        	<div id="map_canvas" style="width:100%; height:300px;"></div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 locations">
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_region_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getRegion()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_province_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getProvince()->getName(); ?></div>
                                                        </div>                                                                                      
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_district_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getDistrict()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_county_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getCounty()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_subcounty_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getSubcounty()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_parish_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getParish()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_village_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getVillage()->getName(); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label"><?php echo $this->translate("global_address_label"); ?>:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo nl2br($member->getAddress1()).''.nl2br($member->getAddress2()); ?></div>
                                                        </div>
                                                        <div class="form-group clearfix">
                                                            <label class="col-md-3 control-label">GPS:</label>
                                                            <div class="col-md-9 nullifempty"><?php echo $member->getGPSCordinates(); ?></div>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </fieldset>                                                                        
                                        </div>
                                    </div>
                                <?php } ?>
                        	</div>
                        </div>
                    </div>
                </div>
            </div>
        </form>   
    </div>                 
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
