<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$title = "SMS Outbound Report";
	$subtitle = 'SMS Report ';
	$datestring = ''; $where_query = '';
	
	$startdate = $request->getParam('startdate');
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
	}
	$senderid = $request->getParam('senderid');
	if(!isEmptyString($senderid)){
		$where_query .= " AND (m.senderid = '".$senderid."' || o.createdby = '".$senderid."') ";
	}
	
	if(!isEmptyString($startdate) && !isEmptyString($enddate)){
		$datestring = '['.changeMySQLDateToPageFormat($startdate).' - '.changeMySQLDateToPageFormat($enddate).']'; 
		$subtitle = $subtitle.'  '.$datestring;		
		$where_query .= " AND (TO_DAYS(o.datecreated) BETWEEN TO_DAYS('".$startdate."') AND TO_DAYS('".$enddate."')) ";
		
		$order = trim($request->order);
		$order_query = " ";
		if(isEmptyString($order)){
			$order = 1;
		}
		if($order == 1){
			$order_query = " ORDER BY o.datecreated DESC ";
		}
		if($order == 2){
			$order_query = " ORDER BY o.phone ASC ";
		}
		if($order == 3){
			$order_query = " ORDER BY o.phone DESC ";
		}
		
		$all_results_query = "SELECT
		o.phone,
		o.msg,
		o.datecreated,
		o.createdby,
		m.senderid,
		IF(u.displayname <> '', u.displayname, concat(u.firstname, ' ', u.lastname, ' ', u.othername)) as sender,
		o.source,
		o.resultcode,
		o.smsid
		from outbox o
		left join message m on (o.messageid = m.id) 
		left join member u on (m.senderid = u.id)
		WHERE o.id <> '' ".$where_query." GROUP BY o.id	".$order_query;
		
		// debugMessage($all_results_query); 
		$conn = Doctrine_Manager::connection(); 
		$result = $conn->fetchAll($all_results_query); // debugMessage($result); 
		$has_no_data = (count($result) == 0) ? true : false;
		// exit;
	}
	
	$this->headTitle($title.$browserappend);
	$description = '';
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Reports / '.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-signal"></span>');
	
	var dateoptions = datepickerOpts;
	var startfrom = '<?php echo date('Y'); ?>';
	dateoptions.yearRange = "-<?php echo date('Y')-2010; ?>:-0"; 
	dateoptions.minDate = "-<?php echo date('Y'); ?>Y";
	dateoptions.maxDate = new Date("Dec 31, "+startfrom);	
	$("#startdate, #enddate").datepicker(dateoptions);
	
	// export list to excel
	$(".submitexcel").click(function(e){
		e.preventDefault();
		var csv_value = $('#datatable').table2CSV({delivery:'value'});
		var decoded_value = base64_encode(csv_value);
		$("#csv_text").val(decoded_value);
		$("#reportform").attr('action', '<?php echo $this->baseUrl('download/excel'); ?>').attr('method', 'post').submit();
		// on submit reset the form parameters to previous definition
		$("#reportform").attr('action', '<?php echo $this->baseUrl("report/reportsearch/page/smsoutbound"); ?>').attr('method', 'get');
		$("#csv_text").val('');
		return true;
	});
	
	$("#filter").click(function(e){
		$.blockUI({ message: '<?php echo $blockcontent; ?>'}); 
		return true;
	});	
	
});
</script>
<div class="row margin0">
    <div class="col-md-12 padding0">
        <form class="form-search makerelative" action="<?php echo $this->baseUrl("report/reportsearch/page/smsoutbound"); ?>" method="get" id="reportform">
        	<?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
			<?php } ?>
            <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
                <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
            <?php } ?>
            <div class="row-fluid clearfix whitebg">
            	<div class="divider10"></div>
                <div class="col-md-9">
                    <ul class="listfilter">
                    	<li><a href="<?php echo $this->baseUrl('report/dashboard'); ?>" class="btn btn-default btn-sm noimgbutton"><i class="glyphicon glyphicon-arrow-left"></i></a></li>
                        <li><input type="text" name="startdate" id="startdate" class="form-control input-sm datefield readonly width100" value="<?php echo $request->startdate; ?>" placeholder="From:" /></li>
                    	<li><input name="enddate" id="enddate" type="text" class="form-control input-sm datefield readonly width100" placeholder="To:" value="<?php echo $request->enddate; ?>" /></li>
                        <li>
							<?php
                                $values = getUsers('', '', '', '', " AND m.status = '1' AND m.type <> '' ");
                                $dropdown = new Zend_Form_Element_Select('senderid',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'Sent By'), $values),
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array("xautofilter", "form-control", 'chosen-select'),
                                                        'style' => 'width:170px;'
                                                    )
                                );  
                                $dropdown->setValue($request->getParam('senderid')); 
                                echo $dropdown->render();
                            ?>
                        </li>
                        <li><button type="submit" class="btn btn-primary btn-sm" title="Generate Report" id="filter"><i class="glyphicon glyphicon-filter"></i> Generate Report</button>
                        	<input type="hidden" name="csv_text" id="csv_text" value="" />
                        </li>
                        <li><a href="<?php echo $this->baseUrl('report/smsoutbound'); ?>">Reset</a></li>
                    </ul>
                </div>
                <div></div>
           	</div>
            <div class="divider10"></div>
            <div id="list_error" class="maxwidth"></div>
    		<div class="row row-bg" style="margin-bottom:10px;">
                <div class="col-sm-12 col-md-12">
                    <div class="widget box makerelative">
                        <div class="widget-header">
                            <h4 class="widgettitle blocked maxwidth"><?php echo $subtitle; ?>
                            <?php if($acl->checkPermission('SMS Outbound Report', ACTION_EXPORT) && !isEmptyString($startdate) && !isEmptyString($enddate)) { ?>	
                                <button type="button" class="btn btn-default btn-xs submitexcel pull-right" tableid="regiontable" style="float:right;"><i class='glyphicon glyphicon-download-alt'></i> Export to Excel</button> &nbsp;
                            <?php } ?>
                            </h4>
                        </div>
                        <div class="widget-content no-padding whitebg minheight400">
                            <?php if(!isEmptyString($startdate) && !isEmptyString($enddate)){ ?>
                                <?php if($has_no_data) { ?>
                                    <div class="divider10"></div>
                                    <div style="clear:both;" class="alert alert-info margin5">There are no records for this report</div>
                                <?php } else { ?>
                                    <div style="width:100%; display:block; height:30px;; position:relative;">
                                        <div class="paginatecustom padding10"><?php echo count($result).' records found'; ?></div>
                                    </div>
                                    
                                    <div class="wrapper1">
                                        <div class="div1" style="width:2000px;"></div>
                                    </div>
                                    <div class="wrapper2" style="max-height:800px; min-height:0; height:auto;">
                                        <div class="div2" style="width:2000px;">
                                            <table class="table list table-bordered table-striped data-table" id="datatable" style="width:auto;">
                                            	<thead class="paginationheader">
                                                	<th style="width:20px;" class="nowrapping centeralign">#</th>
                                                    <th style="width: 130px;" class="nowrapping">Date</th>
                                                    <th style="width: 175px;" class="nowrapping">Sender</th>
                                                    <th style="width: 115px;" class="nowrapping">Phone</th>
                                                    <th style="width: 250px;" class="nowrapping">Message</th>
                                                    <th class="nowrapping">Length</th>
                                                    <th class="nowrapping">SMS ID </th>
                                                    <th style="width: 175px;" class="nowrapping">Result Code</th>
													<th style="width: 150px;" class="nowrapping">Status</th>
                                                </thead>
                                                <tbody>
													<?php
														 $counter = 1;
														 foreach($result as $line){
													?>
                                                    	<tr>
                                                        	<td class="centeralign"><span class="nullifempty"><?php echo $counter; ?></span></td>
                                                            <td><span class="nullifempty"><?php echo formatDateAndTime($line['datecreated']); ?></span></td>
                                                            <td><span class="nullifempty"><?php echo $line['sender']; ?></span></td>
                                                            <td><span class="nullifempty"><?php echo $line['phone']; ?></span></td>
                                                            <td><span class="nullifempty"><?php echo $line['msg']; ?></span></td>
                                                            <td class="centeralign"><span class="nullifempty"><?php echo strlen($line['msg']); ?></span></td>
                                                            <td><span class="nullifempty"><?php echo $line['smsid']; ?></span></td>
                                                            <td><span class="nullifempty"><?php echo $line['resultcode']; ?></span></td>
                                                            <td><span class="nullifempty"><?php //echo $line['resultcode']; ?></span></td>
                                                        </tr>
                                                 	<?php $counter++; } ?>
                                           		</tbody>
                                            </table>
                                        </div>
                                   	</div>
                                <?php } ?>
                            <?php } else { ?>
                                <label class="labeldescription noresults">Select reporting period to Generate</label>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
		</form>
	</div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
