<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$role = new AclGroup();
	$id = decode($request->id);
	
	$resourcearray = getResources();
	$definedactions = ACL::getActions();
	
	if(isEmptyString($request->id)){
		$title = 'New User Role and Permissions';
		$description = '';
		$button_title = $this->translate("global_button_save"); 
		$successmessage = $this->translate('global_save_success');
	} else {
		$role->populate(decode($request->id));
		$title = 'Update Permissions';
		$description = '';
		$button_title = $this->translate("global_button_save");
		$successmessage = $this->translate('global_update_success');
	}
	$posturl = $this->baseUrl("role/processroles");
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$role->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Roles / '.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			name: "required",
			description: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {		
			name: "<?php echo $this->translate("role_name_error"); ?>",
			description: "<?php echo $this->translate("role_description_error"); ?>"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		},
		ignore: ":hidden:not(select)"
	});
	
	// handling of checkbox selections for the permissions
	// bind the function for updating hidden fields when the respective checkboxes are selected
	$("#permissions :checkbox").change(updatePermissionHiddenField); 
													 
	// function to update the value of hidden field when a permission checkbox is selected or unselected
	function updatePermissionHiddenField() {
		if (this.checked) {
			$("#" + this.value).val("1");
		} else {
			$("#" + this.value).val("0");
		} 
	} 
	
	// functionality for the all permissions checkboxes
	// change the odd rows to odd
	$("input[name='allpermissionscheckbox']").click(function() {
		 var id = $(this).attr('id');
		 if(this.checked) {
			 $("."+this.value).attr('checked', true);
			 $("input."+id).val('1');
		 } else {				 
			$("."+this.value).attr('checked', false);
			$("input."+id).val('0');
		 }
		 // trigger a change action on the checkboxes representing the permissions
		 $("." + this.value).trigger("change");
	});
	
	$("#permissions :checkbox").trigger("change");
	$(".resourcetrigger").click(function() {
		var id = $(this).attr('id');
		// alert(id);
		if(this.checked) {
			$("input."+id).val('1');
		} else {				 
			$("input."+id).val('0');
		}
	});
});
</script>
<div class="row-fluid margin0 index">
    <form id="indexform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post">
        <div class="col-md-12 padding0">
            <div class="headerbox">
                <table class="table border0 nohover margin0">                       
                    <tr>		                    
                        <td class="padding2">
                            <button type="submit" class="btn btn-primary savethenview save"><i class="glyphicon glyphicon-ok icon-white"></i> <?php echo $button_title; ?></button>
                            <a class="btn btn-default cancel gonowhere"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <input name="entityname" id="entityname" type="hidden" value="AclGroup" />
        					<input type="hidden" id="id" name="id" value="<?php echo encode($role->getID()); ?>" />
                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="contentcontainer clearfix">
        	<div class="row-fluid marginleft5">
            	<div class="col-md-12">
                    <fieldset class="fieldsetcontainer">
                        <legend>About</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-9">
                            	<div class="row-fluid margin">
                                	<div class="col-md-12 paddingleft0">
                                    	<div class="form-group">
                                            <label class="col-sm-2 control-label"><?php echo $this->translate("global_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control input-sm width300" id="name" name="name" value="<?php echo $role->getName(); ?>" /><div id="name_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2 control-label"><?php echo $this->translate('global_description_label'); ?>:</label>
                                            <div class="col-md-10">
                                                <textarea class="form-control expanding" id="description" name="description"><?php echo $role->getDescription(); ?></textarea>
                                                <div id="description_error"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="fieldsetcontainer">
                        <legend>Permissions</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-12">
                            	<div class="row-fluid margin">
                                	<table class="table table-bordered contentviewtable">
                                        <thead>
                                            <tr>
                                                <th class="xlabel">Resources</th>
                                                <th class="xlabel">All</th> 	
                                                <?php
                                                    foreach($definedactions as $value) {
                                                ?>
                                                <th class="xlabel" style="width:11%; text-align:center;"><?php echo ucfirst($value); ?></th>
                                                <?php 
                                                    } // end creating the header column for each action
                                                ?> 
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                                $counter = 0;
                                                foreach($resourcearray as $resourceid => $resourceName) {
                                                // load the permission instance for the specified resource, since for each group and resource there is only one permission instance
                                                $theresource = new AclResource();
                                                $theresource->populate($resourceid);
                                                // debugMessage($theresource->toArray());
                                                $permission = $role->getPermissionForResource($resourceid); 
                                                // debugMessage($permission->toArray());
                                                
                                                if(!isEmptyString($permission->getID())){
                                                     $resource_ref = $counter;
                                                } else {
                                                    $resource_ref = md5($resourceid); 
                                                }
                                            ?>
                                            <tr>
                                                <td class="xlabel"><?php echo $resourceName; ?>
                                                <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][resourceid]" id="permissions_<?php echo $resource_ref; ?>_resourceid" value="<?php echo $resourceid; ?>" />
                                                <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][id]" id="permissions_<?php echo $resource_ref; ?>_id" value="<?php echo $permission->getID(); ?>" />
                                                <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][groupid]" id="permissions_<?php echo $resource_ref; ?>_groupid" value="<?php echo $role->getID(); ?>" /></td>
                                                <td><input name="allpermissionscheckbox" id="checkall_<?php echo $resourceid; ?>" type="checkbox" value="resource_<?php echo $resourceid; ?>" /></td>                     
                                                <?php 
                                                    foreach($definedactions as $theaction) {
                                                ?>
                                                    <td align="center">
                                                    <?php if ($theresource->get($theaction) == 1) { ?>
                                                        <input type="checkbox" name="chk<?php echo $theaction; ?>[]" id="chk<?php echo $theaction; ?>_<?php echo $resourceid; ?>" value="1" class="resource_<?php echo $resourceid; ?> resourcetrigger" <?php echo $permission->getCheckedStatus($theaction); ?>  />
                                                        <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][<?php echo $theaction; ?>]" id="<?php echo $theaction; ?>_<?php echo $resourceid; ?>" class="chk<?php echo $theaction; ?>_<?php echo $resourceid; ?> checkall_<?php echo $resourceid; ?>" value="<?php echo $permission->checkPermissionForAction($theaction); ?> " />
                                                    <?php } ?>	
                                                    </td>	
                                                <?php } ?>  
                                            </tr>
                                            <?php $counter++; } ?> 
                                        </tbody>                             
                                    </table>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
   		</div>
 	</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
