<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$role = new AclGroup();
	#Populate or retrive the entry using the above id. 
	$role->populate(decode($request->id)); // debugMessage($role->toArray());
	
    $resourcearray = getResources();
	$definedactions = ACL::getActions();
	
	$title = 'Role Permissions';
	$description = $role->getName()." - ".$role->getDescription();
	$listurl = $this->baseUrl("role/list");
	$listitems  = "Roles";
	$this->headTitle($role->getName().$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Role / '.$role->getName(); ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
	
});
</script>
<div class="row-fluid margin0 view">
    <div class="col-md-12 padding0">
    	<div class="headerbox">
            <table class="table border0 nohover margin0">                       
                <tr>		                    
                    <td class="padding2">
                    	<div class="btn-group gridactions">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle noround" data-toggle="dropdown">Actions <span class="caret"></span></button>
                            <ul class="dropdown-menu" role="menu" style="left:-86px;">
                                <?php if ($acl->checkPermission('Role', ACTION_EDIT)) { ?>	
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('role/index/id/'.encode($role->getID())); ?>" id="update"><i class="glyphicon glyphicon-pencil"></i>&nbsp; Update</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission('Role', ACTION_LIST)) { ?>
                                    <li><a class="blockanchor" href="<?php echo $listurl; ?>"><i class="glyphicon glyphicon-list"></i>&nbsp; List Roles</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission('Role', ACTION_DELETE)) { ?>	
                                    <li><a class="deleteline gonowhere" action="<?php echo $this->baseUrl('role/delete/id/'.encode($role->getID())."/entityname/AclGroup/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete Entry"><i class="glyphicon  glyphicon-trash"></i>&nbsp; Delete</a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php if($sessionhaserror) { ?>
        <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <div class="contentcontainer clearfix">
    	<form id="viewform" class="form-horizontal" role="form" method="get">
        	<div class="row-fluid margin0">
            	<div class="col-md-12">
                    <fieldset class="fieldsetcontainer">
                        <legend><?php echo $role->getName(); ?> - Permissions</legend>
                        <div class="panel-body well-sm">
                            <table class="table contentviewtable">
                                <thead>
                                    <tr>
                                        <th class="xlabel">Resources</th>                    	
                                        <?php
                                            foreach($definedactions as $value) {
                                        ?>
                                        <th class="xlabel" style="width:11%; text-align:center;"><?php echo ucfirst($value); ?></th>
                                        <?php 
                                            } // end creating the header column for each action
                                        ?> 
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                        foreach($resourcearray as $resourceid => $resourceName) {
                                        // load the permission instance for the specified resource, since for each group and resource there is only one permission instance
                                        $theresource = new AclResource();
                                        $theresource->populate($resourceid);
                                        //debugMessage($resource->toArray());
                                        $permission = $role->getPermissionForResource($resourceid); 
                                    ?>
                                    <tr>
                                        <td class="xlabel"><?php echo $resourceName; ?></td>                            
                                        <?php 
                                            foreach($definedactions as $theaction) {
                                                if($theresource->get($theaction) == 1) {
                                        ?>
                                                <td align="center">
                                                    <?php echo ($permission->checkPermissionForAction($theaction) ? 
                                                    '<img src="'.$this->baseUrl("images/tick.png").'" alt="Permission Granted" />' : 
                                                    '<img src="'.$this->baseUrl("images/cross.png").'" alt="Permission Denied" />');  
                                                    ?>
                                                </td>                        
                                        <?php } else { ?>
                                                <td>&nbsp;</td>     
                                        <?php 
                                                }// end checking if there are available permissions
                                            } // end creating checkboxes for each available action
                                        ?>  
                                    </tr><?php 
                                    } // end creating a row for each resource
                                    ?> 
                                </tbody>                             
                            </table>
                		</div>
               		</fieldset>
              	</div>
        	</div>
		</form>
	</div>                   
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>