<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$type = $request->type;
	$pageview = $request->show;
	$style = '1';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	$title = $this->translate("location_pagetitle_list");
	$listitems = $this->translate("location_pagetitle_list");
	$listurl = $this->baseUrl("location/list");
	$addurl = $this->baseUrl("location");
	$moduleitem = "Location";
	if(isEmptyString($type)){
		$type = '0';
	}
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	switch($type){
		case 0:
			$paginate->setSearchColumns(array("l.name"));
			$paginate->setFilterColumns(array());
			$paginate->setDefaultSortBy("l.name");	
			$paginate->setItemCountPerPage('ALL');
			break;
		case 1:
			$paginate->setItemCountPerPage('ALL');
			$paginate->setSearchColumns(array("l.name"));
			$paginate->setFilterColumns(array());
			$paginate->setDefaultSortBy("l.name");	
			break;
		case 2:
			$paginate->setSearchColumns(array("l.name"));
			$paginate->setFilterColumns(array());
			$paginate->setDefaultSortBy("l.name");	
			$paginate->setItemCountPerPage('ALL');
			break;
		case 3:
		case 4:
		case 5:
		case 6:
			$paginate->setSearchColumns(array("l.name"));
			$paginate->setFilterColumns(array());
			$paginate->setDefaultSortBy("l.name");	
			$paginate->setItemCountPerPage('50');
			break;
		case 7:
			$paginate->setSearchColumns(array("l.name","p.name"));
			$paginate->setFilterColumns(array());
			$paginate->setDefaultSortBy("l.name");	
			$paginate->setItemCountPerPage('ALL');
			break;
		default:
			break;
	}
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE l.id <> '' ";
	$provincesql1 = " "; $provincesql2 = " ";
	$allowclear = false;
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (l.`name` LIKE '".$request->letter."%') ";
		$allowclear = true;
	}
	
	$isregion = false; $isprovince = false; $isdistrict = false; $iscounty = false; $issubcounty = false; $isparish = false; $isvillage = false;
	if(!isEmptyString($type)){
		if($type != 0 && $type !=7){
			$where_query .= " AND (l.locationtype = '".$type."') ";
		}
		$addurl = $this->baseUrl("location/index/type/".$type);
		$listurl = $this->baseUrl("location/list/type/".$type);
		switch($type){
			case 0:
			case 1:
				$moduleitem = "Region";
				$listitems = "Regions";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("region_pagetitle_list");	
				$isregion = true;
				$customfields = " ";
				$customjoin = " ";
				break;
			case 2:
				$moduleitem = "District";
				$listitems = "Districts";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("district_pagetitle_list");
				$isdistrict = true;
				$customfields = " r.`name` as region, pv.name as province, ";
				$customjoin = " LEFT JOIN region r on (l.nfbpcregionid = r.id) LEFT JOIN province pv on (l.provinceid = pv.id) ";
				break;
			case 3:
				$moduleitem = "County";
				$listitems = "Counties";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("county_pagetitle_list");
				$iscounty = true;
				$customfields = " ";
				$customjoin = " ";
				break;
			case 4:
				$moduleitem = "Subcounty";
				$listitems = "Subcounties";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("subcounty_pagetitle_list");
				$issubcounty = true; 
				$customfields = " ";
				$customjoin = " ";
				break;
			case 5:
				$moduleitem = "Parish";
				$listitems = "Parishes";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("parish_pagetitle_list");
				$isparish = true; 
				$customfields = " ";
				$customjoin = " ";
				break;
			case 6:
				$moduleitem = "Village";
				$listitems = "Villages";
				$moduleitem_lower = strtolower($moduleitem);
				$title = $this->translate("village_pagetitle_list");
				$isvillage = true;
				$customfields = " ";
				$customjoin = " ";
				break;
			case 7:
				$moduleitem = "Province";
				$listitems = "Provinces";
				$moduleitem_lower = strtolower($moduleitem);
				$title = 'Provinces';
				$isprovince = true;
				$provincesql1 = ", GROUP_CONCAT(DISTINCT p.name ORDER BY p.name ASC SEPARATOR ',') as provinces, GROUP_CONCAT(DISTINCT p.id ORDER BY p.name ASC SEPARATOR ',') as provinceids ";
				$provincesql2 = " LEFT JOIN province p on (p.regionid = l.id) ";
				$customfields = " ";
				$customjoin = " ";
				break;
			default:
				break;
		}
		$leveltwoname = $listitems;
	}
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$regionid = $request->regionid;
	if(!isEmptyString($regionid)){
		if($isprovince){
			$where_query .= " AND p.regionid = '".$regionid."' ";
		} else {
			$where_query .= " AND l.nfbpcregionid = '".$regionid."' ";
		}
	}
	
	$districtid = $request->districtid;
	if(!isEmptyString($districtid)){
		$where_query .= " AND l.districtid = '".$districtid."' ";
	}
	
	$countyid = $request->countyid;
	if(!isEmptyString($countyid)){
		$where_query .= " AND l.countyid = '".$countyid."' ";
	}
	
	$subcountyid = $request->subcountyid;
	if(!isEmptyString($subcountyid)){
		$where_query .= " AND l.subcountyid = '".$subcountyid."' ";
	}
	
	$parishid = $request->parishid;
	if(!isEmptyString($parishid)){
		$where_query .= " AND l.parishid = '".$parishid."' ";
	}
	
	$order = trim($request->order);
	$order_query = " ORDER BY l.name ASC ";
	if($isparish || $isvillage){
		$order_query = " ORDER BY l.datecreated DESC ";
	}
	if(isEmptyString($order)){
		$order = 1;
	}
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(u.firstname,' ',u.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	if($type == 0 || $type == 7){
		$all_results_query = "SELECT l.id as lid, l.code as Code, l.name as `Name`, l.description as `Description` ".$provincesql1." FROM region l ".$provincesql2."
		".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY l.id ".$order_query;
	} else {
		$all_results_query = "SELECT l.id as lid, l.code as Code, l.name as `Name`, l.description as `Description`, l.locationtype, l.regionid, l.nfbpcregionid, l.provinceid, l.districtid, l.countyid, l.subcountyid, l.parishid, ".$customfields." d.`name` as district, c.`name` as county, s.`name` as subcounty, p.`name` as parish
		FROM location l
		LEFT JOIN location d on (l.districtid = d.id and d.locationtype = 2)
		".$customjoin."
		LEFT JOIN location c on (l.countyid = c.id and c.locationtype = 3)
		LEFT JOIN location s on (l.subcountyid = s.id and s.locationtype = 4)
		LEFT JOIN location p on (l.parishid = p.id and p.locationtype = 5)
		".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY l.id ".$order_query;
	}
	// debugMessage($all_results_query); exit;
	
	// determine total number of records found
	$conn = Doctrine_Manager::connection(); 
	if($type == 0 || $type == 7){
		$count_query = "SELECT count(l.id) as total FROM region l ".$provincesql2." ".$where_query." ".$paginate->getSearchAndFilterSQL(); // debugMessage($count_query); 
	} else {
		$count_query = "SELECT count(l.id) as total FROM location l ".$where_query." ".$paginate->getSearchAndFilterSQL(); // debugMessage($count_query); 
	}
	$total = $conn->fetchOne($count_query);
	$paginate->setItemCount($total); //debugMessage('>> '.$total);	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	// exit;
	//$paginate->setItemCountFromSQLQuery($all_results_query);
	// $current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false;
	
	$description = '';
	$icon = $this->baseUrl('images/icon_home.png');
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-map-marker"></span>');
		
		$(".switchregion").change(function(){
			window.location.href = $(this).attr('href');
			$.blockUI({ message: uiblockcontent}); 
		});
	});
</script>
<style>
<?php if($isprovince){ ?>
.peoplelist .peoplewrapper {
	height:130px;
}
<?php } else { ?>
.peoplelist .peoplewrapper {
	height:100px;
}
<?php } ?>
a.updatelink {
	text-decoration:none;
	color:#333;
	<?php if($isvillage){ ?>
	font-weight:normal;
	<?php } ?>
}
</style>
<div class="row margin0">
    <div class="col-md-12 padding0">
    <form class="form margin0 listform makerelative" action="<?php echo $this->baseUrl("location/listsearch"); ?>" method="get" id="listform">
		<?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="row-fluid clearfix">
        	<div class="col-md-9 paddingleft0">
            	<ul class="listfilter">
					<?php if ($acl->checkPermission('Location', ACTION_CREATE)) { ?>
                        <li><a class="btn btn-primary btn-sm blockanchor" href="<?php echo $addurl; ?>"><i class="glyphicon glyphicon-plus"></i> Add New <?php echo $moduleitem; ?></a></li>
                    <?php } ?>
                    <?php if($isregion || $isprovince){ ?>
	                    <li>
                            <label class="radio-inline"><input class="switchregion <?php echo $type == 0 ? 1 : 0; ?>" type="radio" name="region" id="region_0" value="0" href="<?php echo $this->baseUrl('location/list/type/0'); ?>" /> <?php echo getCompanyName(); ?> Regions </label>
                            <label class="radio-inline"><input class="switchregion <?php echo $type == 7 ? 1 : 0; ?>" type="radio" name="region" id="provinces" value="7" href="<?php echo $this->baseUrl('location/list/type/7'); ?>" /> <?php echo getCompanyName(); ?> Provinces</label>
                        </li>
                    <?php } ?>
                    <?php if($isdistrict){ ?>
                        <li>
                        	<label class="control-label blocked" style="width:150px;">Search By Region</label>
                        	<?php
								$regions = getNFBPCRegions();
								$dropdown = new Zend_Form_Element_Select('regionid',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'All Regions'), $regions),								
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("autofilter", "form-control", 'chosen-select', 'col-md-2')
													)
												);
								$dropdown->setValue($request->getParam('regionid')); 
								echo $dropdown->render();
							?> 
                            
                        </li>
                    <?php } ?>
                    <?php if($iscounty || $issubcounty || $isparish || $isvillage){ ?>
                        <li>
                        	<label class="control-label blocked" style="width:150px;">Search By District</label>
                        	<?php
								$districts = getDistricts($request->getParam('regionid'));
								$dropdown = new Zend_Form_Element_Select('districtid',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'All Districts'), $districts),								
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("autofilter", "form-control", 'chosen-select', 'col-md-2'),
														'style' => 'width:150px;'
													)
												);
								$dropdown->setValue($request->getParam('districtid')); 
								echo $dropdown->render();
							?> 
                            
                        </li>
                    <?php } ?>
                    <?php if($issubcounty || $isparish || $isvillage){ ?>
                        <li>
                        	<label class="control-label blocked" style="width:150px;">Search By County</label>
                        	<?php
								$counties = getCountiesInDistrict($request->getParam('districtid'));
								$dropdown = new Zend_Form_Element_Select('countyid',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'All Counties'), $counties),								
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("autofilter", "form-control", 'chosen-select', 'col-md-2'),
														'style' => 'width:170px;'
													)
												);
								$dropdown->setValue($request->getParam('countyid')); 
								echo $dropdown->render();
							?> 
                            
                        </li>
                    <?php } ?>
                    <?php if($isparish || $isvillage){ ?>
                        <li>
                        	<label class="control-label blocked" style="width:170px;">Search By Sub-county</label>
                        	<?php
								$subcounties = getSubCounties($request->getParam('countyid'));
								$dropdown = new Zend_Form_Element_Select('subcountyid',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'All Sub-counties'), $subcounties),								
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("autofilter", "form-control", 'chosen-select', 'col-md-2'),
														'style' => 'width:170px;'
													)
												);
								$dropdown->setValue($request->getParam('subcountyid')); 
								echo $dropdown->render();
							?> 
                            
                        </li>
                    <?php } ?>
                    <?php if($isvillage){ ?>
                        <li>
                        	<label class="control-label blocked" style="width:170px;">Search By Parish</label>
                        	<?php
								$parishes = getParishes($request->getParam('subcountyid'));
								$dropdown = new Zend_Form_Element_Select('parishid',
													array(
														'multiOptions' => array_merge_maintain_keys(array('' => 'All Parishes'), $parishes),								
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("autofilter", "form-control", 'chosen-select', 'col-md-2'),
														'style' => 'width:170px;'
													)
												);
								$dropdown->setValue($request->getParam('parishid')); 
								echo $dropdown->render();
							?> 
                            
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-md-3 padding0">
            	<div class="col-md-12 padding0"><input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." /><button type="submit" class="btn btn-default blockanchor searchbtn"><i class="glyphicon glyphicon-search"></i></button></div>
            	<input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                <input type="hidden" name="type" id="type" value="<?php echo $type; ?>" />
                <input type="hidden" name="style" id="style" value="<?php echo $style; ?>" />
                <?php if($allowclear){ ?>
                    <a href="<?php echo $listurl; ?>" title="Clear Search and Filters" class="reset close button btn resetlink blockanchor">&times;</a>
                <?php } ?>
            </div>
        </div>
        <div class="divider10"></div>
        <div class="stylewidget">
            <a class="gonowhere btn btn-default btn-xs noround styletrigger <?php echo $style == 1 ? 'active' : ''; ?>" id="style1" rel='1'><i class="glyphicon glyphicon-th-large"></i> Grid</a>
            <a class="gonowhere btn btn-default btn-xs noround styletrigger <?php echo $style == 2 ? 'active' : ''; ?>" id="style2" rel='2'><i class="glyphicon glyphicon-list-alt"></i> Table</a>
        </div>
        <?php if($isdistrict || $iscounty || $issubcounty || $isparish || $isvillage){ ?>
        	<?php echo $paginate->getAlphabetString(); ?>
        <?php } ?>
		<?php if ($has_no_data) { ?>
            <div class="divider30"></div>
            <div style="clear:both;" class="alert alert-warning margin5"><?php echo $this->translate("global_list_noentries"); ?></div>
        <?php } else { ?>
        	<div class="row-fluid peoplelist clearfix makerelative <?php echo $style == '2' ? 'whitebg' : ''; ?>">
            	<div class="divider10"></div>
                <?php if($style == 1){ ?>
                	<?php
						$counter = 1; 				  		
						foreach($result as $line){
							$id = $line['lid'];	
							$viewurl = '';
							if($isregion && $type == 0){
								$viewurl = $this->baseUrl('location/list/type/7/regionid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/0/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/0/id/'.encode($line['lid']));
							}
							if($isprovince){
								$viewurl = $this->baseUrl('location/list/type/2/regionid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/7/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/7/id/'.encode($line['lid']));
							}
							if($isdistrict){
								$viewurl = $this->baseUrl('location/list/type/3/districtid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/2/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/2/id/'.encode($line['lid']));
							}
							if($iscounty){
								$viewurl = $this->baseUrl('location/list/type/4/districtid/'.$line['districtid'].'/countyid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/3/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/3/id/'.encode($line['lid']));
							}
							if($issubcounty){
								$viewurl = $this->baseUrl('location/list/type/5/districtid/'.$line['districtid'].'/countyid/'.$line['countyid'].'/subcountyid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/4/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/4/id/'.encode($line['lid']));
							}
							if($isparish){
								$viewurl = $this->baseUrl('location/list/type/6/districtid/'.$line['districtid'].'/countyid/'.$line['countyid'].'/subcountyid/'.$line['subcountyid'].'/parishid/'.$id);
								$indexurl = $this->baseUrl('location/index/type/5/id/'.encode($line['lid']));	
								$detailsurl = $this->baseUrl('location/view/type/5/id/'.encode($line['lid']));
							}
							if($isvillage){
								$indexurl = $this->baseUrl('location/index/type/6/id/'.encode($line['lid']));	
								$detailsurl = $viewurl = $this->baseUrl('location/view/type/6/id/'.encode($line['lid']));
							}
							
							$listarray = array(); $subtitle = '';
							if($isprovince){
								$provincelist = $line['provinces'];
								$subtitle = 'Provinces';
								if(!isEmptyString($provincelist)){
									$listarray = explode(',', $provincelist);
								}
								
								$provinceidlist = $line['provinceids'];
								if(!isEmptyString($provinceidlist)){
									$listidsarray = explode(',', $provinceidlist);
								}
							}
						?>
                        <div class="col-xs-12 col-sm-6 xpaddingleft0">
                            <div class="peoplewrapper makerelative">
                            	<?php if(!$isprovince){ ?>
                                    <div class="btn-group gridactions">
                                        <button type="button" class="btn btn-default btn-xs dropdown-toggle noround" data-toggle="dropdown">Action <span class="caret"></span></button>
                                        <ul class="dropdown-menu" role="menu" style="left:-102px;">
                                            <?php if ($acl->checkPermission('Location', ACTION_VIEW)) { ?>
                                                <li><a class="blockanchor" href="<?php echo $detailsurl; ?>"><i class="glyphicon glyphicon-list"></i> View Profile</a></li>
                                            <?php } ?>
                                            <?php if ($acl->checkPermission('Location', ACTION_EDIT)) { ?>
                                                <li><a class="blockanchor" href="<?php echo $indexurl; ?>"><i class="glyphicon glyphicon-pencil"></i> Update</a></li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                <?php } ?>
                                <div class="peopleinfo" style="margin-left:0;">
                                    <h4><a href="<?php echo $viewurl; ?>" class="<?php echo in_array($type, array(1)) ? 'blanklink updatelink' : 'blockanchor'; ?>"><?php echo $line['Name']; ?></a></h4>
                                    <div class="col-md-12 padding0">
                                        <div class="divider5"></div>
                                        <?php if($isprovince){ ?>
                                            <span class="bolded blocked" style="font-size:12px; text-decoration:underline;"><?php echo $subtitle; ?></span>
                                            <ul>
                                                <?php if(count($listarray) == 0){?>
                                                    <li class="nullifempty"></li>
                                                <?php } else { ?>
                                                    <?php foreach($listarray as $key => $item){ 
														
													?>
                                                        <li class="nullifmpty" style="display:block; width:50%; float:left; font-size:14px; margin-bottom:2px; list-style:outside;"><a class="blockanchor" href="<?php echo $this->baseUrl('location/view/type/7/id/'.encode($listidsarray[$key])); ?>"><?php echo $item; ?></a></li> 
                                                    <?php } ?>
                                                <?php } ?>
                                            </ul>
                                        <?php } ?>
                                        <div class="col-md-6 padding0">
                                            <ul>
                                                <?php if($isdistrict){ ?>
                                                    <li><span class="bolded">Region:</span> <span class="nullifempty"><?php echo $line['region']; ?></span></li>
                                                <?php } ?>
                                                <?php if($isdistrict){ ?>
                                                    <li><span class="bolded">Province:</span> <span class="nullifempty"><?php echo $line['province']; ?></span></li>
                                                <?php } ?>
												<?php if($iscounty || $issubcounty || $isparish || $isvillage){ ?>
                                                    <li><span class="bolded">District:</span> <span class="nullifempty"><?php echo $line['district']; ?></span></li>
                                                <?php } ?>
                                                <?php if($issubcounty || $isparish || $isvillage){ ?>
                                                    <li><span class="bolded">County:</span> <span class="nullifempty"><?php echo $line['county']; ?></span></li> 
                                                <?php } ?>
                                            </ul>
                                        </div>
                                        <div class="col-md-5 padding0">
                                            <ul>
                                                <?php if($isparish || $isvillage){ ?>
                                                    <li><span class="bolded">Sub-county:</span> <span class="nullifempty"><?php echo $line['subcounty']; ?></span></li>
                                                <?php } ?>
                                                <?php if($isvillage){ ?>
                                                    <li><span class="bolded">Parish:</span> <span class="nullifempty"><?php echo $line['parish']; ?></span></li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                   <?php } ?> 
                <?php } ?> 
				<?php if($style == 2){ ?>
                	<div class="wrapper1">
                        <div class="div1" style="width:1500px;"></div>
                    </div>
                    <div class="wrapper2">
                        <div class="div2" style="width:1500px;">
                            <table class="table list table-bordered table-striped data-table" id="datatable">
                                <thead class="paginationheader">
                                    <th class="nowrapping">Actions <img style="width:10px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /> </th>
                                    <th class="nowrapping">Code# <img style="width:40px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                    <?php if($isprovince){ ?>
                                        <th class="nowrapping">Region <img style="width:75px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <th class="nowrapping" style="width:99%;">Provinces <img style="width:75px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                    <?php } else { ?>
                                        <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('l.name', 'Name of '.$moduleitem); ?><img style="width:125px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php if($isdistrict){ ?>
                                            <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('r.name', 'Region'); ?><img style="width:75px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                            <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('pv.name', 'Province'); ?><img style="width:75px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php } ?>
                                        <?php if($iscounty || $issubcounty || $isparish || $isvillage){ ?>
                                        	<th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('d.name', 'District'); ?><img style="width:75px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php } ?>
                                        <?php if($issubcounty || $isparish || $isvillage){ ?>
                                        	<th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('c.name', 'County'); ?><img style="width:120px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php } ?>
                                        <?php if($isparish || $isvillage){ ?>
                                        	<th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('s.name', 'Sub-county'); ?><img style="width:120px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php } ?>
                                        <?php if($isvillage){ ?>
                                        	<th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('p.name', 'Parish'); ?><img style="width:120px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                        <?php } ?>
                                        <th class="nowrapping" style="width:99%;">Description <img style="width:250px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                    <?php } ?>
                                </thead>
                                <tbody>
                                    <?php
                                        $counter = 1; 				  		
                                        foreach($result as $line){
                                            $id = $line['lid'];	
                                            $viewurl = '';
                                            if($isregion && $type == 0){
                                                $viewurl = $this->baseUrl('location/list/type/7/regionid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/0/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/0/id/'.encode($line['lid']));
                                            }
                                            if($isprovince){
                                                $viewurl = $this->baseUrl('location/list/type/2/regionid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/7/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/7/id/'.encode($line['lid']));
                                            }
                                            if($isdistrict){
                                                $viewurl = $this->baseUrl('location/list/type/3/districtid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/2/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/2/id/'.encode($line['lid']));
                                            }
                                            if($iscounty){
                                                $viewurl = $this->baseUrl('location/list/type/4/districtid/'.$line['districtid'].'/countyid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/3/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/3/id/'.encode($line['lid']));
                                            }
                                            if($issubcounty){
                                                $viewurl = $this->baseUrl('location/list/type/5/districtid/'.$line['districtid'].'/countyid/'.$line['countyid'].'/subcountyid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/4/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/4/id/'.encode($line['lid']));
                                            }
                                            if($isparish){
                                                $viewurl = $this->baseUrl('location/list/type/6/districtid/'.$line['districtid'].'/countyid/'.$line['countyid'].'/subcountyid/'.$line['subcountyid'].'/parishid/'.$id);
                                                $indexurl = $this->baseUrl('location/index/type/5/id/'.encode($line['lid']));	
                                                $detailsurl = $this->baseUrl('location/view/type/5/id/'.encode($line['lid']));
                                            }
                                            if($isvillage){
                                                $indexurl = $this->baseUrl('location/index/type/6/id/'.encode($line['lid']));	
                                                $detailsurl = $viewurl = $this->baseUrl('location/view/type/6/id/'.encode($line['lid']));
                                            }
                                            
                                            
                                            $listarray = array(); $subtitle = '';
                                            if($isprovince){
                                                $provincelist = $line['provinces'];
                                                $subtitle = 'Provinces';
                                                if(!isEmptyString($provincelist)){
                                                    $listarray = explode(',', $provincelist);
                                                }
                                                
                                                $provinceidlist = $line['provinceids'];
                                                if(!isEmptyString($provinceidlist)){
                                                    $listidsarray = explode(',', $provinceidlist);
                                                }
                                            }
                                        ?>
                                            <tr>
                                                <td>
                                                    <ul class="nav listactions">
                                                        <?php if ($acl->checkPermission('Location', ACTION_VIEW)) { ?>
                                                            <li><a class="blockanchor" href="<?php echo $detailsurl; ?>" title="View"><i class="glyphicon glyphicon-list"></i></a></li>
                                                        <?php } ?>
                                                        <?php if ($acl->checkPermission('Location', ACTION_EDIT)) { ?>
                                                            <li><a class="blockanchor" href="<?php echo $indexurl; ?>" title="Update"><i class="glyphicon glyphicon-pencil"></i> </a></li>
                                                        <?php } ?>
                                                    </ul>
                                                </td>
                                                <td class="nullifmpty"><?php echo $line['Code']; ?></td>
                                                <?php if($isprovince){ ?>
                                                    <td class="nullifmpty"><a href="<?php echo $viewurl; ?>" class="<?php echo in_array($type, array(1,6)) ? 'blanklink updatelink' : 'blockanchor'; ?>"><?php echo $line['Name']; ?></a></td>
                                                    <th class="nullifempty" style="font-weight:normal;">
                                                        <?php if(count($listarray) > 0){?>
                                                            <?php echo implode(', ',$listarray); ?>
                                                        <?php } ?>
                                                    </th>
                                                <?php } else { ?>
                                                    <td class="nullifmpty"><a href="<?php echo $viewurl; ?>" class="<?php echo in_array($type, array(1,6)) ? 'blanklink updatelink' : 'blockanchor'; ?>"><?php echo $line['Name']; ?></a></td>
                                                    <?php if($isdistrict){ ?>
                                                        <td class="nullifmpty"><?php echo $line['region']; ?></td>
                                                        <td class="nullifmpty"><?php echo $line['province']; ?></td>
                                                    <?php } ?>
                                                    <?php if($iscounty || $issubcounty || $isparish || $isvillage){ ?>
                                                    	<td class="nullifmpty"><?php echo $line['district']; ?></td>
                                                    <?php } ?>
                                                    <?php if($issubcounty || $isparish || $isvillage){ ?>
                                                    	<td class="nullifmpty"><?php echo $line['county']; ?></td>
                                                    <?php } ?>
                                                    <?php if($isparish || $isvillage){ ?>
                                                    	<td class="nullifmpty"><?php echo $line['subcounty']; ?></td>
                                                    <?php } ?>
                                                    <?php if($isvillage){ ?>
                                                    	<td class="nullifmpty"><?php echo $line['parish']; ?></td>
                                                    <?php } ?>
                                                    <td class="nullifmpty"><?php echo $line['Description']; ?></td>
                                                <?php } ?>
                                            </tr>
                                        <?php } ?>  
                                </tbody>
                            </table>
                    	</div>
                    </div>
                <?php } ?>        
            </div>
            <div class="row-fluid">
                <div class="table-footer">
                    <div class="col-md-6 padding0" style="margin-bottom:10px;">
                        <div class="table-actions">
                            <div class="row col-md-12 margin0 padding0 clearfix">
                                <div class="col-md-6 padding0 floatleft"><?php echo $paginate->getListCountDropDown(); ?></div>
                                <div class="col-md-6 paddingleft5 rightalign" style="margin-bottom:5px;"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 padding0">
                        <?php echo $paginate->getPaginationLinks(); ?>
                    </div>
                </div>
            </div>
        <?php } ?>
	</form>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
