 			<br /><br />
            <?php echo "<br />".$this->signoffname."<br />".$this->signoffemail; ?>
        </td>
    </tr>
</table>
<table style="width:800px; margin:0;">	
    <tr>
    	<td style="padding:0; margin:0; background-color:#428BCA; color:#ffffff; padding-top:10px; padding-bottom:10px; padding-left:10px; font-family: Arial, Helvetica, Tahoma, sans-serif; font-size:15px;"><a style="color:#ffffff;" href="<?php echo $this->serverUrl($this->baseUrl()); ?>"><?php echo $this->serverUrl($this->baseUrl()); ?></a></td>
    </tr>
</table>