<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$title = "Application Error";
	$description = "Runtime error occured. Contact Admin";
 
 	//print_r('Error is : ');
	//debugMessage($this->message);
	
	$this->headTitle($title.$browserappend); 
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/bootstrap-3.1.1.min.css')); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/bootstrap-theme.css')); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/custom.css')); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/app.css')); ?>">
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/jquery-1.11.1.min.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/bootstrap-3.1.1.min.js')); ?>"></script>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.'Error'; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
		
	});
</script>
<div class="divider30"></div>
<div class="row-fluid">
	<div class="col-md-12">
		<div class="alert alert-danger">Application Runtime Error</div>
		<p class="bg-warning padding10"><?php echo $this->message; ?></p>
    </div>
</div>    
<?php 
	echo $session->getVar(APPLICATION_ERROR_PAGE_MESSAGE); 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>