<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("profile_pagetitle_changepassword");
	$this->headTitle($title); 
	
	$user = new Member(); 	
	$user->populate(decode($request->id)); // debugMessage($user->toArray());
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$user->processPost($session->getVar(FORM_VALUES));	
	}

	$this->headTitle($title);
?>
<script>
	$(document).ready(function() {		
		
		$.validator.addMethod("new_password_not_old", function(value, element) {
			var oldpass = $("#oldpassword").val();
			if(oldpass != "" && value == oldpass){
				return false;
			}		
			return true
		}, "New password should be different from current password");
	
		// add the validation for wholesale price to be less than retail price
		$.validator.addMethod("iscurrent", function(value, element, params) {
			var pass = '<?php echo $user->getPassword(); ?>';
			var hashed = sha1(value);
			if (pass == hashed) {
				return true; 
			}
			return false;        
		}, "Invalid current password");
		
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				oldpassword: {
					required: true,
					iscurrent:true				
				},
				password: {
					required: true,
					new_password_not_old: true,
					maxlength: <?php echo $config->profile->passwordmaxlength; ?>,
					minlength: <?php echo $config->profile->passwordminlength; ?>
				},
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}				
			}, 
			// the messages for each of the fields being validated
			messages: {				
				oldpassword: {
					required: "<?php echo $this->translate("profile_oldpassword_error"); ?>"
				},
				password: {
					required: "<?php echo $this->translate("profile_new_password_error"); ?>",
					maxlength: "<?php echo sprintf($this->translate("profile_password_error_maxlength"), $config->profile->passwordmaxlength); ?>",
					minlength: "<?php echo sprintf($this->translate("profile_password_error_minlength"), $config->profile->passwordminlength); ?>"			
				}, 
				confirmpassword: {
					required: "<?php echo $this->translate("profile_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("profile_confirmpassword_error_equalto"); ?>"
				}
			}
		});
	}); 
</script>
<div class="popupdiv">
<form class="form-horizontal well col-md-12 clearfix" id="indexform" method="post">
    <table class="table margin0 noborder">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
		<tr>
            <td width="30%"><label class="control-label pull-left"><?php echo $this->translate("profile_password_current_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input name="oldpassword" id="oldpassword" type="password" class="span3 hastooltipx" /><div id="oldpassword_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label pull-left"><?php echo $this->translate("profile_password_new_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input name="password" id="password" type="password" class="span3 hastooltipx" /><div id="password_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label pull-left"><?php echo $this->translate("profile_password_confirm_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input name="confirmpassword" id="confirmpassword" type="password" class="span3 hastooltipx" /><div id="confirmpassword_error"></div>
            	<input type="hidden" name="entityname" value="Member" />
                <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
            </td>
        </tr>
	</table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>