<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new Member();
	$type = trim($request->type);
	$allroles = getUserType();
	$successurl = encode($this->baseUrl('profile/view'));
	
	if (isEmptyString($request->id)) {
		$title = "New User";  // default title
		$posturl = $this->baseUrl("profile/create");
		$button_title = $this->translate("global_button_save");
		$successmessage = $this->translate('global_save_success');
		$failureurl =  encode($this->baseUrl('profile/index'));
		if(isEmptyString($type)){
			$type = DEFAULT_USER_GROUP;
		}
		// $user->setType($type);
		$title = isEmptyString($request->type) ? "New User": "New ".$allroles[$type];
		$breadcrumbtitle = 'New User'; 
	} else {
		$title = "Update Profile"; 		
		$user->populate(decode($request->id));		
		$posturl = $this->baseUrl("profile/edit"); 
		$button_title = $this->translate('global_button_save_changes'); 
		$successmessage = $this->translate('global_update_success');
		$type = $user->getType();
		if(isEmptyString($type)){
			$type = $user->getUserGroups()->get(0)->getGroupID();
		}
		$failureurl =  encode($this->baseUrl('profile/index/id/'.encode($user->getID())));
		$breadcrumbtitle = $user->getName();  
	}
	
	$isme = false; 
	if($userid == $user->getID()){
		$isme = true; 
	}
	
	$states = getStates();
	$counties = getAllCounties();
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$user->processPost($session->getVar(FORM_VALUES));	
	}
	
	$viewurl = $this->baseUrl('profile/view/id/'.encode($user->getID()));
	$indexurl = $this->baseUrl('profile/index/id/'.encode($user->getID()));
	$listurl = $this->baseUrl('profile/list');
	$listitems = $this->translate("profile_list_items");
	$description = '';
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Users / '.$breadcrumbtitle; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
	
	// custom date picker options
	var dateofbirthOpts = datepickerOpts;
	var startfrom = '<?php echo date('Y'); ?>';
	dateofbirthOpts.yearRange = "-<?php echo date('Y')-1900; ?>:-0"; 
	dateofbirthOpts.minDate = "-<?php echo date('Y'); ?>Y";
	datepickerOpts.maxDate = new Date("Dec 31, "+startfrom);	
	$("#dateofbirth").datepicker(dateofbirthOpts);
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			gender: {
				required: true
			},
			firstname: {
				required: true
			},
			lastname: {
				required: true
			},
			username: {
				required: <?php echo $user->isUserActive() ? 'true' : 'false' ; ?>, 
				minlength: <?php echo $config->profile->usernameminlength; ?>,
				maxlength: <?php echo $config->profile->usernamemaxlength; ?>
			},
			email: {
				required: <?php echo $user->isUserActive() ? 'true' : 'false' ; ?>, 
				email: true
			},
			oldpassword: {
				required: function(element) {
					return !isEmptyString($("#newpassword").val());
				}
			},
			newpassword: {
				<?php if(isEmptyString($user->getID())) { ?>
					required: true,
				<?php } else { ?>
					required: function(element) {
						return !isEmptyString($("#oldpassword").val());
					},
				<?php } ?>	
				maxlength: <?php echo $config->profile->passwordmaxlength; ?>,
				minlength: <?php echo $config->profile->passwordminlength; ?>
			},			
			confirmpassword: {
				<?php if(isEmptyString($user->getID())) { ?>
					required: true,
				<?php } else { ?>
					required: function(element) {
						return !isEmptyString($("#oldpassword").val()) && !isEmptyString($("#newpassword").val());
					},
				<?php } ?>	
				equalTo: "#newpassword"
			},
			type: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {		
			gender: {
				"required": "<?php echo $this->translate("profile_gender_error"); ?>"
			}, 
			firstname: {
				"required": "<?php echo $this->translate("profile_firstname_error"); ?>"
			},
			lastname: {
				"required": "<?php echo $this->translate("profile_lastname_error"); ?>"
			},
			username: {
				required: "<?php echo $this->translate("profile_username_error"); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_username_error_minlength"), $config->profile->usernameminlength); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_username_error_maxlength"), $config->profile->usernamemaxlength); ?>"
			},
			email: {
				required: "<?php echo $this->translate("profile_email_error"); ?>", 
				email: "<?php echo $this->translate("profile_email_invalid_error"); ?>"
			},
			oldpassword: {
				required: "<?php echo $this->translate("profile_oldpassword_error"); ?>"
			},
			newpassword: {
				required: "<?php echo $this->translate("profile_password_error"); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_password_error_maxlength"), $config->profile->passwordmaxlength); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_password_error_minlength"), $config->profile->passwordminlength); ?>"
			},
			confirmpassword: {
				required: "<?php echo $this->translate("profile_confirmpassword_error"); ?>",
				equalTo: "<?php echo $this->translate("profile_confirmpassword_error_equalto"); ?>"
			},
			type: "<?php echo $this->translate("profile_role_error"); ?>"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		}
	});
	
	// prevent copy and paste in password fields
	$('input.password').bind('copy paste', function (e) {
	   e.preventDefault();
	});
		
	<?php if(!isEmptyString($user->getID())) { ?>
		$('.password').attr('placeholder', 'Leave empty if no password change'); 
		$('.disableonedit').attr('readonly', true).attr('disabled', true);
	<?php } ?>
	
	//when button is clicked  
	$('#check_username_availability').click(function(){ 
		check_user_availability();  
	});
	$('#username').change(function(){ 
		check_user_availability();  
	});  
	$('#username').keyup(function(){
		this.value = this.value.toLowerCase();
	});
	
	//function to check username availability  
	function check_user_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var username = $('#username').val();  
		if(!isEmptyString(username) && username.length >= 4 && username.length <= 15 && isAlpha(username)){
			// alert('passed');
			$('#username_availability_result').html(checking_html); 
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkusername'); ?>", { username: username, userid: userid },  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the username is available
						$('#username_availability_result').html(username + ' is NOT available!').addClass('alert').addClass('alert-danger').removeClass('alert-success'); 
					} else {  
						//show that the username is NOT available  
						$('#username_availability_result').html(username + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger');
					}  
			});   
		}
	}
	
	//when button is clicked  
	$('#check_email_availability').click(function(){ 
		check_email_availability();  
	});
	$('#email').change(function(){ 
		check_email_availability();  
	});  
	
	//function to check email availability  
	function check_email_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var email = $('#email').val();  
		if(!isEmptyString(email) && validateEmail(email)){
			$('#email_availability_result').html(checking_html);  
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkemail'); ?>", { email: email, userid: userid},  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the email is available
						$('#email_availability_result').html(email + ' is NOT available!').addClass('alert').addClass('alert-danger').removeClass('alert-success fade in'); 
					} else {  
						//show that the email is NOT available  
						$('#email_availability_result').html(email + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger fade in');
					}  
			});  
		}
	}
	
}); 
</script>
<div class="row-fluid margin0 index">
    <form id="indexform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post">
        <div class="col-md-12 padding0">
            <div class="headerbox">
                <table class="table border0 nohover margin0">                       
                    <tr>		                    
                        <td class="padding2">
                            <button type="submit" class="btn btn-primary savethenview save"><i class="glyphicon glyphicon-ok icon-white"></i> <?php echo $button_title; ?></button>
                            <a href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID())); ?>" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <input type="hidden" name="entityname" value="Member" />
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                            <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="general" />
                            <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="general" />
                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="contentcontainer clearfix">
        	<div class="row-fluid margin0">
            	<div class="col-md-12" style="margin-top:10px;">
                    <fieldset class="fieldsetcontainer">
                        <legend>About</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-9">
                            	<div class="row-fluid margin">
                                	<div class="col-md-6 paddingleft0">
                                    	<div class="form-group">
                                            <label class="col-sm-5 control-label"><?php echo $this->translate("profile_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control input-sm" id="firstname" name="firstname" value="<?php echo $user->getFirstName(); ?>" /><div id="firstname_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-5 control-label"><?php echo $this->translate("profile_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control input-sm" id="lastname" name="lastname" value="<?php echo $user->getLastName(); ?>" /><div id="lastname_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-5 control-label"><?php echo $this->translate("profile_initial_label"); ?>: </label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control input-sm width75" id="initial" name="initial" value="<?php echo $user->getInitial(); ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-5 control-label"><?php echo $this->translate("profile_gender_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-7">
                                                <label class="radio-inline"><input type="radio" name="gender" id="male" value="1" class="xform-control <?php echo $user->getGender() == '1'? 1 : 0; ?>"> Male</label>
                                            	<label class="radio-inline"><input type="radio" name="gender" id="female" value="2" class="xform-control <?php echo $user->getGender() == '2'? 1 : 0; ?>"> Female</label>
                                            	<div id="gender_error"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                    	<div class="form-group">
                                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_dob_label"); ?>:</label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control input-sm datefield readonly width100" name="dateofbirth" id="dateofbirth" value="<?php echo changeMySQLDateToPageFormat($user->getDateofBirth()); ?>" />    
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_ssn_label"); ?>:</label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control input-sm" id="ssn" name="ssn" value="<?php echo $user->getSSN(); ?>" />
                                            	<div id="ssn_error"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                            	<div id="profileinfo"> 
                                    <img id="profileimage" class="img-thumbnail img-responsive" style="max-width:140px;" src="<?php echo $user->getMediumPicturePath(); ?>" />
                                </div>                                                        
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row-fluid margin0">
            	<div class="col-md-6" style="margin-top:10px;">
                    <fieldset class="fieldsetcontainer clearfix" id="location" style="min-height:280px;">
                        <legend>Address</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_addressline1_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm" id="addressline1" name="addressline1" value="<?php echo $user->getAddressline1(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_addressline2_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm" id="addressline2" name="addressline2" value="<?php echo $user->getAddressline2(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_city_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width200" id="city" name="city" value="<?php echo $user->getCity(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_state_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <?php
											$dropdown = new Zend_Form_Element_Select('state',
																array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $states),
																	'view' => new Zend_View(),
																	'decorators' => array('ViewHelper'),
																	'class' => array('form-control','input-sm','width200')
																)
											);  
											$dropdown->setValue($user->getState()); 
											echo $dropdown->render();
										?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_zipcode_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width100" id="zipcode" name="zipcode" value="<?php echo $user->getZipCode(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_county_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <?php
											$dropdown = new Zend_Form_Element_Select('county',
																array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $counties),
																	'view' => new Zend_View(),
																	'decorators' => array('ViewHelper'),
																	'class' => array('form-control','input-sm','width200')
																)
											);  
											$dropdown->setValue($user->getCounty()); 
											echo $dropdown->render();
										?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6" style="margin-top:10px;">
                    <fieldset class="fieldsetcontainer clearfix" id="contact" style="min-height:280px;">
                        <legend>Contact</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_homephone_label"); ?>:</label>
                                    <div class="col-sm-8">
                                       <input type="text" class="form-control input-sm width150" id="home" name="home" value="<?php echo $user->getHome(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_cellphone_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width150" id="cell" name="cell" value="<?php echo $user->getCell(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_workphone_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width150" id="work" name="work" value="<?php echo $user->getWork(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_workext_label"); ?>:</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width75" id="ext" name="ext" value="<?php echo $user->getExt(); ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-5 control-label">&nbsp;</label>
                                    <div class="col-sm-7">&nbsp;</div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row-fluid margin0">
            	<div class="col-md-12" style="margin-top:10px;">
                    <fieldset class="fieldsetcontainer">
                        <legend>Settings and Prefferences</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_type_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <div class="col-sm-8">
                                        <?php
                                            $allvalues = getUserType();
                                            $dropdown = new Zend_Form_Element_Select('type',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('form-control','input-sm','width200')
                                                                )
                                            );  
                                            $dropdown->setValue($user->getType()); 
                                            echo $dropdown->render();
                                        ?><div id="type_error"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_username_label"); ?>: <?php echo !$user->isUserActive() ? '' : $this->translate("global_required_field_marker"); ?></label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control input-sm width200 inline" id="username" name="username" value="<?php echo $user->getUserName(); ?>" /> <a class="btn btn-sm btn-default gonowhere" id='check_username_availability' title="Check Availability">Check</a>
                                        
                                       	<div id="username_availability_result" style="margin-top:4px"></div>
                                        <div id="username_error"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate("profile_email_label"); ?>: <?php echo !$user->isUserActive() ? '' : $this->translate("global_required_field_marker"); ?></label>
                                    <div class="col-sm-8">
                                    	<input type="hidden" name="oldemail" id="oldemail" value="<?php echo $user->getEmail(); ?>" />
                                        <input type="text" class="form-control input-sm width225 inline" id="email" name="email" value="<?php echo $user->getEmail(); ?>" />
                                        <a class="btn btn-sm btn-default gonowhere" id='check_email_availability' title="Check Availability">Check</a>
                                        <div id="email_availability_result" style="margin-top:4px"></div>
                                        <?php if($user->isUserInActive()){ ?>
                                            <label class="checkbox-inline"><input type="checkbox" name="isinvited" id="isinvited" value="1" /> Invite via Email:</label>
                                        <?php } ?>
                                        <div id="email_error"></div>
                                    </div>
                                </div>
                                <?php if(!isEmptyString($user->getPassword())){ ?>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label"><?php echo $this->translate("profile_password_current_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                                        <div class="col-sm-6 paddingright0">
                                            <input type="password" name="oldpassword" id="oldpassword" class="form-control password input-sm xwidth200" autocomplete="off" />
                                            <div id="oldpassword_error"></div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?php if(!isEmptyString($user->getID())){ ?>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label"><?php echo !isEmptyString($user->getPassword()) ? $this->translate("profile_password_new_label") : $this->translate("profile_password_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                                        <div class="col-sm-6 paddingright0">
                                             <input type="password" name="newpassword" id="newpassword" class="form-control password input-sm xwidth200" autocomplete="off" onkeyup="passwordStrength(this.value)" />
                                            <input type="hidden" name="trx" id="trx"  value="<?php echo $user->getPassword(); ?>" />
                                            <p style="display:inline-block; float:right;">
                                                <label for="passwordStrength" class="hidden">Password strength</label>
                                                <div id="passwordDescription" style="width:100px;">strength</div>
                                                <div id="passwordStrength" class="strength0"></div>
                                            </p>
                                            <div id="newpassword_error"></div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label blocked"><?php echo $this->translate("profile_password_confirm_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                                        <div class="col-sm-6 paddingright0">
                                            <input type="password" name="confirmpassword" id="confirmpassword" class="form-control password input-sm xwidth200" /><div id="confirmpassword_error"></div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"></label>
                                    <div class="col-sm-8">
                                        
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"></label>
                                    <div class="col-sm-8">
                                        
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"></label>
                                    <div class="col-sm-8">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="divider15"></div>
   		</div>
 	</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
