<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("profile_pagetitle_recoverpassword"); 
	$this->headTitle($title);

	$button_title = $this->translate("profile_button_recoverpassword");
	$posturl = $this->baseUrl("user/processrecoverpassword");
	
	$user = new Member(); 
	$user->populate(decode($request->id));
	
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$user->setEmail($formvalues['email']); 
	}
?>
<script>
$(document).ready(function() {			
	$(".navonlogin, #sidebar, .breadcrumbs li").remove();
	$("#indexform").validate({
		rules: {
			email: {
				required: true
			}
		}, 
		messages: {
			email: {
				required: "<?php echo $this->translate("profile_email_error"); ?>"
			}
		}
	}); 
	
	<?php if(!isEmptyString($request->id)){ ?>
		// if admin user is resetting a user's password, automatically submit form.	 	
		$("#indexform").submit();
	<?php } ?>
}); 
</script>
<style>
.breadcrumbs li, .pageheader, #headercontainer #headermenu, #headercontainer #headerright {
	display:none;
}
</style>
<div id="publiccontainer" class="index">
	<!--<h3 class="centeralign">Account Activation</h3>-->
	<?php if ($sessionhaserror) { ?>
    	<div class="divider10"></div>
    	<div class="alert alert-danger fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
	<?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <form id="indexform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post">
    	<fieldset class="fieldsetcontainer">
            <legend><h4><?php echo $title; ?></h4></legend>
            <div class="panel-body well-sm">
            	<div class="divider20"></div>
            	<table class="table">
                	<tr>
                        <td colspan="2"><label class="control-label">Provide your Identity (Email or Username or Phone) and we will send you instructions on how to recover your Password</label>
                        <div class="divider10"></div></td>  
                    </tr>
                    <tr>
                        <td colspan="2"><input name="email" id="email" placeholder="Enter your Acount Identity here" type="text" class="form-control input-sm" value="<?php echo $user->getEmail(); ?>" />
                        <div class="divider20"></div></td>
                    </tr>
                    <tr>
                       <td colspan="2">
                            <button id="reset" class="btn btn-primary btn-sm" type="submit"><i class="glyphicon glyphicon-ok"></i> <?php echo $this->translate("profile_button_recoverpassword"); ?></button>
                            <input name="id" id="id" type="hidden" value="<?php echo encode($user->getID()); ?>" />
                       </td>
                   </tr>
                </table>
          	</div>
       	</fieldset>
    </form>
</div>    
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
