<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Reset Password";
	$this->headTitle($title); 
		
	$user = new Member(); 
	$user->populate(decode($request->id));
	
	#in case of errors in session, populate the fields from session
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$user->setEmail($formvalues['email']); 
	}
	
	$this->headTitle($title.$browserappend); 
?>
<script>
$(document).ready(function() {			
	$(".navonlogin, #sidebar, .breadcrumbs li").remove();
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			password: {
				required: true,
				maxlength: <?php echo $config->profile->passwordmaxlength; ?>,
				minlength: <?php echo $config->profile->passwordminlength; ?>
			},			
			confirmpassword: {
				required: true,
				equalTo: "#password"
			},
			username: {
				required: true, 
				minlength: <?php echo $config->profile->usernameminlength; ?>,
				maxlength: <?php echo $config->profile->usernamemaxlength; ?>
			}
		}, 
		messages: {
			password: {
				required: "<?php echo $this->translate("profile_password_error"); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_password_error_maxlength"), $config->profile->passwordmaxlength); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_password_error_minlength"), $config->profile->passwordminlength); ?>"		
			},
			confirmpassword: {
				required: "<?php echo $this->translate("profile_confirmpassword_error"); ?>",
				equalTo: "<?php echo $this->translate("profile_confirmpassword_error_equalto"); ?>"
			},
			username: {
				required: "<?php echo $this->translate("profile_username_error"); ?>", 					
				minlength: "Username must have atleast <?php echo $config->profile->usernameminlength; ?> characters",
				maxlength: "Username must not exceed <?php echo $config->profile->usernamemaxlength; ?> characters"
			}
		}
	});		
}); 
</script>
<style>
.breadcrumbs li, .pageheader, #headercontainer #headermenu, #headercontainer #headerright {
	display:none;
}
</style>
<div id="publiccontainer" class="index">
	<!--<h3 class="centeralign">Account Activation</h3>-->
	<?php if($sessionhaserror) { ?>
    	<div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
    	<div class="alert alert-success clear"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <form id="indexform" class="form-horizontal" role="form" action="<?php echo $this->baseUrl("user/processresetpassword"); ?>" method="post">
        <fieldset class="fieldsetcontainer">
            <legend><h4><?php echo $title; ?></h4></legend>
            <div class="panel-body well-sm">
            	<table class="table">
                   <tr>
                       <td><label class="control-label username"><?php echo $this->translate("profile_username_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                       <td><input name="username" id="username" type="text" class="span2" value="<?php echo $user->getUsername(); ?>" /></td>
                   </tr>
                   <tr>
                       <td><label class="control-label password"><?php echo $this->translate("profile_password_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                       <td><input name="password" id="password" type="password" autocomplete="off" class="span2 password xhastooltip" onkeyup="passwordStrength(this.value)" value="" />
                       <p style="display:inline-block; float:right;">
                            <label for="passwordStrength" class="hidden">Password strength</label>
                            <div id="passwordDescription" style="width:100px;">strength</div>
                            <div id="passwordStrength" class="strength0"></div>
                        </p>
                       <div id="password_error" class="clear"></div></td>
                   </tr>
                   <tr>
                       <td><label class="control-label confirmpassword"><?php echo $this->translate("profile_password_confirm_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                       <td><input name="confirmpassword" id="confirmpassword" autocomplete="off" type="password" class="span2 password xhastooltip" value="" title="<?php //echo $this->translate("profile_confirmpassword_tooltip"); ?>" />
                       <div id="confirmpassword_error"></div></td>
                   </tr>
                   <tr>
                       <td></td>
                       <td>
                            <button id="reset" class="btn btn-primary xbtn-large" type="submit" title="Save Password"><i class="icon-lock icon-white"></i> Save Password</button><input name="id" type="hidden" value="<?php echo encode($user->getID()); ?>" />
                       </td>
                   </tr>
                </table>
            </div>
		</fieldset>
	</form>
</div>                   
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
