<?php 
									$style = '1'; $isuserlist = false; $ismemberlist = true;
									if(!isEmptyString($request->style)){
										$style = $request->style;
										$session->setVar('style', $request->style);
									}
									if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
										$style = $session->getVar('style');
									}
									
									$paginate = new Pagination();	
									$paginate->setView($this);
									# set the search columns to be used on this list
									$paginate->setSearchColumns(array("m.firstname","m.lastname","m.email","m.phone","m.phone2","m.othername","m.displayname"));
									$paginate->setFilterColumns(array());
									$paginate->setItemCountPerPage("50");
									
									# define the letter to be clicked to ease navigation 
									$where_query = " WHERE m.id <> '' AND m.organisationid = '".$organisation->getID()."' ";
									$allowclear = false;
										
									if(!isEmptyString($request->letter)){
										$where_query .= " AND (m.`firstname` LIKE '".$request->letter."%' OR m.`lastname` LIKE '".$request->letter."%') ";
										$allowclear = true;
									}
									
									if(!isEmptyString($request->searchterm)){
										$allowclear = true;
									}
									
									$order = trim($request->order);
									$order_query = " ";
									$order_query = " ORDER BY m.datecreated DESC, m.id desc ";
									
									$sortcolumn = $request->sortby;
									$sortorder = $request->sortorder;
									if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
										$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
									}
									// f.orgname as fundername, concat(u.firstname,' ',u.lastname) as supervisorname
									$paginate->processPost($request->getParams());
									$all_results_query = "SELECT 
										m.id as mid, 
										m.firstname, m.lastname, m.othername, m.displayname as Member, IF(m.displayname <> '', m.displayname, concat(m.firstname, ' ', m.lastname, ' ', m.othername)) as name, m.username,
										m.phone, m.phone2, m.email, 
										m.profilephoto, m.gender, m.dateofbirth, m.bio, 
										m.datecreated as mdatecreated, m.createdby as mcreatedby, m.activationdate,
										m.nationality, m.country,m.address1 as address1,o.name as church,
										m.status as `status`, m.salutation, m.profession, m.organisationid,
										r.name as region,p.name as province,d.name as district,c.name as county,s.name as subcounty,ps.name as parish, v.name as village,
										m.website, m.dateofbirth, m.dateofbirth, m.contactid, m.noofchildren,
										ms.contactname as contactname, mc.displayname as addedby,
										g.groupid as groupid, acg.name as `Group`, group_concat(t.name separator ', ') as committees
									 FROM member m
									 left join organisation o on (m.organisationid = o.id)
									 left join region r on (m.regionid = r.id) 
									 left join province p on (m.provinceid = p.id) 
									 left join location d on (m.districtid = d.id and d.locationtype = 2)
									 left join location c on (m.countyid = c.id and c.locationtype = 3)
									 left join location s on (m.subcountyid = s.id and s.locationtype = 4)
									 left join location ps on (m.parishid = ps.id and ps.locationtype = 5)
									 left join location v on (m.villageid = v.id and v.locationtype = 6)
									 left join member mc on (m.createdby = mc.id)
									 left join member ms on (m.contactid = ms.id)
									 left join aclusergroup as g ON (m.id = g.userid) 
									 left join aclgroup as acg ON (g.groupid = acg.id)
									 left join appointment as a on (a.memberid = m.id)
									 left join committee as t on (a.committeeid = t.id)
									 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY m.id ".$order_query;
									
									// debugMessage($all_results_query); // exit;
									
									// determine total number of records found
									$conn = Doctrine_Manager::connection(); 
									$count_query = "SELECT count(m.id) as total FROM member m
									  	 left join organisation o on (m.organisationid = o.id)
										 left join region r on (m.regionid = r.id) 
										 left join province p on (m.provinceid = p.id) 
										 left join location d on (m.districtid = d.id and d.locationtype = 2)
										 left join location c on (m.countyid = c.id and c.locationtype = 3)
										 left join location s on (m.subcountyid = s.id and s.locationtype = 4)
										 left join location ps on (m.parishid = ps.id and ps.locationtype = 5)
										 left join location v on (m.villageid = v.id and v.locationtype = 6)
										 left join member mc on (m.createdby = mc.id)
										 left join member ms on (m.contactid = ms.id)
										 left join aclusergroup as g ON (m.id = g.userid) 
										 left join aclgroup as acg ON (g.groupid = acg.id)
									".$where_query." ".$paginate->getSearchAndFilterSQL(); // debugMessage($count_query); 
									$total = $conn->fetchOne($count_query);
									$paginate->setItemCount($total); //debugMessage('>> '.$total);	
									$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
									
									$conn = Doctrine_Manager::connection(); 
									$result = $conn->fetchAll($current_results_query);
									$has_no_data = (count($result) == 0) ? true : false;
								?>
                                <div class="divider10"></div>
                                <div class="row-fluid clearfix">
                                    <div class="col-md-9 paddingleft0">
                                        <ul class="listfilter blocked">
                                            <?php if ($acl->checkPermission('Organisation', ACTION_CREATE)) { ?>
                                                <li><a title="Add Church Member" class="btn btn-primary btn-sm blockanchor" href="<?php echo $this->baseUrl('member/index/churchid/'.$organisation->getID()); ?>"><i class="glyphicon glyphicon-plus"></i> Add Church Member</a></li>
                                            <?php } ?>
                                            <?php if ($acl->checkPermission('Member', ACTION_EXPORT)) { ?>
                                                <button type="button" class="btn btn-default btn-xs noround submitexcel" title="Export to Excel"><i class='glyphicon glyphicon-download-alt'></i> Export</button>
                                                <input type="hidden" name="csv_text" id="csv_text" value="" />
                                            <?php } ?>
                                        </ul>
                                    </div>
                                    <div class="col-md-3 padding0">
                                        <div class="col-md-12 padding0"><input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." /><button type="submit" class="btn btn-default blockanchor searchbtn"><i class="glyphicon glyphicon-search"></i></button></div>
                                        <input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                                        <input type="hidden" name="style" id="style" value="<?php echo $style; ?>" />
                                        <?php if($allowclear){ ?>
                                            <a href="<?php echo $memberlisturl; ?>" title="Clear Search and Filters" class="reset close button btn resetlink blockanchor">&times;</a>
                                        <?php } ?>
                                    </div>
                                </div>
                                <?php if ($has_no_data) { ?>
                                    <div class="divider10"></div>
                                    <div style="clear:both;" class="alert alert-warning margin5"><?php echo $this->translate("global_list_noentries"); ?></div>
                                <?php } else { ?>
                                	<div class="wrapper1">
                                        <div class="div1" style="width:3700px;"></div>
                                    </div>
                                    <div class="wrapper2">
                                        <div class="div2" style="width:3700px;">
                                            <table class="table list table-bordered table-striped data-table" id="datatable">
                                                <thead class="paginationheader">
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.id',  'Ref#'); ?>
                                                        <img style="width:55px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /> </th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.displayname',  'Full Name'); ?>
                                                        <img style="width:150px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.phone', 'Phone'); ?>
                                                        <img style="width:50px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.email', 'Email'); ?>
                                                        <img style="width:150px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.gender', 'Gender'); ?></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.nationality', 'Nationality'); ?>
                                                        <img style="width:15px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.country', 'Country'); ?>
                                                        <img style="width:30px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.nfbpcregionid', 'Region'); ?>
                                                        <img style="width:150px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.provinceid', 'Province'); ?>
                                                        <img style="width:80px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.districtid', 'District'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.countyid', 'County'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.subcountyid', 'Sub-county'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.parishid', 'Parish'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.villageid', 'Village'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.address1', 'Address'); ?>
                                                        <img style="width:200px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.salutation', 'Title'); ?>
                                                        <img style="width:30px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.profession', 'Profession'); ?>
                                                        <img style="width:60px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.dateofbirth', 'Date of Birth'); ?>
                                                        <img style="width:60px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.datecreated', 'Registration Date'); ?>
                                                        <img style="width:50px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                    <th class="nowrapping"><?php echo $paginate->getSortLinkForColumn('m.createdby', 'Registered By'); ?>
                                                        <img style="width:100px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                </thead>
                                                <tbody>
                                                    <?php
														$salutations = getSalutations();
														$professions = getProfessions();
														$allstatus = getUserStatus();
                                                        foreach($result as $line){
                                                            $viewurl = $this->baseUrl($controller.'/view/id/'.encode($line['mid']));
                                                            $indexurl = $this->baseUrl($controller.'/index/id/'.encode($line['mid']));
                                                    ?>
                                                        <tr>
                                                            <td class="nullifempty"><a href="<?php echo $viewurl; ?>" class="blockanchor"><?php echo 'M'.number_pad($line['mid'], 4); ?></a></td>
                                                            <td class="nullifempty"><?php echo $line['Member']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['phone']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['email']; ?></td>
                                                            <td class="nullifempty"><?php echo getGenderText($line['gender']); ?></td>
                                                            <td class="nullifempty"><?php echo $line['country'] == 'UG' ? 'Ugandan': ''; ?></td>
                                                            <td class="nullifempty"><?php echo $line['country'] == 'UG' ? 'Uganda': ''; ?></td>
                                                            <td class="nullifempty"><?php echo $line['region']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['province']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['district']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['county']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['subcounty']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['parish']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['village']; ?></td>
                                                            <td class="nullifempty"><?php echo $line['address1']; ?></td>
                                                            <td class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['salutation'], $salutations) ? '' : $salutations[$line['salutation']]; ?></td>
                                                            <td class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['profession'], $professions) ? '' : $professions[$line['profession']]; ?></td>
                                                            <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['dateofbirth']); ?></td>
                                                            <td class="nullifempty"><?php echo formatDateAndTime($line['mdatecreated']); ?></td>
                                                            <td class="nullifempty"><?php echo $line['addedby']; ?></td>
                                                        </tr>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="divider10"></div>
                                    <div class="col-md-4 padding0">
                                        <div class="leftalign"><label class="form-control"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></label></div>
                                    </div>
                                    <div class="col-md-8 padding0">
                                        <div class="inline floatleft"><?php echo $paginate->getPaginationLinks(); ?></div>
                                        <div class="inline floatright"><?php // echo $this->listcountdropdown; ?></div>
                                    </div>
                                <?php } ?>